# Adm Homework 3

## 1.Data Collection

### 1.1. Get the list of master's degree courses



In [1]:
#importing librairies

import requests
from bs4 import BeautifulSoup
import os
import pandas as pd
import time
import random
import re
import lxml
from lxml import html
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service


## 1.Data Collection
### 1.1. Get the list of master's degree courses

In [2]:
#creating an empty list to store urls
data=[]

#looping through the 400 first pages of the website
for i in range(1,401):
    url_temp = "https://www.findamasters.com/masters-degrees/msc-degrees/"
    page = "?PG=" + str(i)
    url = url_temp + page

    # Sending an HTTP request to the URL and then get the HTML content
    response = requests.get(url)

    # Check if the request was successful (status code 200)
    if response.status_code == 200:
        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(response.content, "html.parser")

        # Example: Extracting all the links on the page
        links = str(soup.find_all("a"))
        new = links.split('<a class="courseLink text-dark" href=')
        k=0
        for j in new:
            if j.startswith('"/master'):
                temp = j.split(" title")
                temp_2=temp[0]
                temp_2=temp_2[1:-1]
                final_url = "https://www.findamasters.com" + temp_2
                print(final_url)
                data.append(final_url)
            
    else:
        print(f"Failed to retrieve the webpage. Status code: {response.status_code}")


https://www.findamasters.com/masters-degrees/course/3d-design-for-virtual-environments-msc/?i93d2645c19223
https://www.findamasters.com/masters-degrees/course/accounting-and-finance-msc/?i321d3232c3891
https://www.findamasters.com/masters-degrees/course/accounting-and-finance-msc/?i280d4409c4025
https://www.findamasters.com/masters-degrees/course/accounting-accountability-and-financial-management-msc/?i132d7816c25522
https://www.findamasters.com/masters-degrees/course/accounting-financial-management-and-digital-business-msc/?i345d4286c351
https://www.findamasters.com/masters-degrees/course/actuarial-management-msc/?i393d8527c62946
https://www.findamasters.com/masters-degrees/course/actuarial-science-msc/?i393d8527c62945
https://www.findamasters.com/masters-degrees/course/addictions-msc/?i132d4318c27100
https://www.findamasters.com/masters-degrees/course/adult-and-mental-health-nursing-pre-registration-msc/?i393d8906c42735
https://www.findamasters.com/masters-degrees/course/adult-nursin

https://www.findamasters.com/masters-degrees/course/construction-economics-and-management-msc/?i274d3503c19992
https://www.findamasters.com/masters-degrees/course/construction-law-and-dispute-resolution-msc/?i132d5324c17040
https://www.findamasters.com/masters-degrees/course/construction-management-msc/?i393d8904c8719
https://www.findamasters.com/masters-degrees/course/construction-project-management-msc/?i149d8880c69648
https://www.findamasters.com/masters-degrees/course/corporate-finance-msc/?i393d8528c62951
https://www.findamasters.com/masters-degrees/course/creative-industries-and-cultural-policy-msc/?i307d4953c35275
https://www.findamasters.com/masters-degrees/course/criminology/?i280d1689c71197
https://www.findamasters.com/masters-degrees/course/criminology-and-criminal-justice-msc/?i228d7665c56512
https://www.findamasters.com/masters-degrees/course/criminology-and-criminal-justice-msc/?i393d4030c11635
https://www.findamasters.com/masters-degrees/course/cyber-security-msc/?i93d26

https://www.findamasters.com/masters-degrees/course/finance-technology-and-policy-msc/?i300d3321c53463
https://www.findamasters.com/masters-degrees/course/financial-economics-msc/?i393d4030c11656
https://www.findamasters.com/masters-degrees/course/financial-policy-and-regulation-msc-pg-dip-pg-cert/?i132d7816c70345
https://www.findamasters.com/masters-degrees/course/financial-risk-management-msc/?i250d5075c45741
https://www.findamasters.com/masters-degrees/course/financial-technology-msc/?i112d3962c54902
https://www.findamasters.com/masters-degrees/course/food-innovation-msc/?i309d8786c67993
https://www.findamasters.com/masters-degrees/course/food-policy-msc/?i393d8906c34146
https://www.findamasters.com/masters-degrees/course/food-science-msc/?i321d3236c2752
https://www.findamasters.com/masters-degrees/course/forensic-psychology-msc/?i201d5836c53329
https://www.findamasters.com/masters-degrees/course/forensic-science-msc-mres/?i132d4846c58512
https://www.findamasters.com/masters-degrees

https://www.findamasters.com/masters-degrees/course/maritime-operations-and-management-msc/?i393d8904c42733
https://www.findamasters.com/masters-degrees/course/maritime-safety-and-security-management-msc/?i393d8904c70295
https://www.findamasters.com/masters-degrees/course/marketing-digital-marketing-msc/?i345d4286c42214
https://www.findamasters.com/masters-degrees/course/marketing-msc/?i280d4409c11026
https://www.findamasters.com/masters-degrees/course/master-in-food-systems/?i3516d8598c64381
https://www.findamasters.com/masters-degrees/course/master-in-global-logistics-and-supply-chain-management/?i869d5886c72048
https://www.findamasters.com/masters-degrees/course/master-in-global-management-at-esmt-berlin/?i543d6894c35093
https://www.findamasters.com/masters-degrees/course/master-in-health-care-management/?i2741d7927c52539
https://www.findamasters.com/masters-degrees/course/master-of-business-administration/?i2988d8109c55002
https://www.findamasters.com/masters-degrees/course/master-

https://www.findamasters.com/masters-degrees/course/msc-criminology-and-criminal-psychology/?i1268d6475c41745
https://www.findamasters.com/masters-degrees/course/msc-cyber-security/?i1268d6475c62568
https://www.findamasters.com/masters-degrees/course/msc-cyber-security-online/?i326d8583c65051
https://www.findamasters.com/masters-degrees/course/msc-cyber-security-and-digital-forensics/?i343d8475c64490
https://www.findamasters.com/masters-degrees/course/msc-cybercrime/?i343d8475c61736
https://www.findamasters.com/masters-degrees/course/msc-data-analytics/?i348d602c42568
https://www.findamasters.com/masters-degrees/course/msc-data-analytics/?i343d8475c61737
https://www.findamasters.com/masters-degrees/course/msc-data-science/?i1268d6475c69031
https://www.findamasters.com/masters-degrees/course/msc-data-science/?i394d8872c71390
https://www.findamasters.com/masters-degrees/course/msc-data-science-and-artificial-intelligence-online/?i326d8583c65053
https://www.findamasters.com/masters-degree

https://www.findamasters.com/masters-degrees/course/msc-islamic-finance/?i296d1445c56576
https://www.findamasters.com/masters-degrees/course/msc-law-and-sustainability/?i888d5925c69721
https://www.findamasters.com/masters-degrees/course/msc-logistics-and-supply-chain-management/?i315d8200c56798
https://www.findamasters.com/masters-degrees/course/msc-management/?i348d3109c66493
https://www.findamasters.com/masters-degrees/course/msc-management/?i2678d7714c70232
https://www.findamasters.com/masters-degrees/course/msc-management-online/?i326d8583c65056
https://www.findamasters.com/masters-degrees/course/msc-management-with-optional-specialization/?i394d8872c71606
https://www.findamasters.com/masters-degrees/course/msc-marketing-and-retail-innovation/?i272d4706c61478
https://www.findamasters.com/masters-degrees/course/msc-marketing-practice/?i272d4706c20747
https://www.findamasters.com/masters-degrees/course/msc-materials-science-and-engineering/?i348d644c22980
https://www.findamasters.com

https://www.findamasters.com/masters-degrees/course/political-communication-msc-pgdip/?i307d4959c9982
https://www.findamasters.com/masters-degrees/course/political-economy-of-emerging-markets-msc/?i132d2510c27535
https://www.findamasters.com/masters-degrees/course/precision-medicine-genomic-data-science-msc/?i321d8431c54925
https://www.findamasters.com/masters-degrees/course/preventative-cardiovascular-medicine-msc/?i1705d6873c42558
https://www.findamasters.com/masters-degrees/course/primary-care-practice-nursing-msc-pgdip-graddip/?i393d8906c42746
https://www.findamasters.com/masters-degrees/course/product-design-engineering-msc/?i309d3273c67824
https://www.findamasters.com/masters-degrees/course/project-and-enterprise-management-msc/?i274d3503c20017
https://www.findamasters.com/masters-degrees/course/project-management-finance-and-risk-msc/?i393d8904c23573
https://www.findamasters.com/masters-degrees/course/prosperity-innovation-and-entrepreneurship-msc/?i274d7388c59559
https://www.fi

https://www.findamasters.com/masters-degrees/course/accountancy/?i106d8166c67626
https://www.findamasters.com/masters-degrees/course/accountancy-and-controlling-msc/?i1114d7097c57582
https://www.findamasters.com/masters-degrees/course/accounting-master-of-science-ms/?i512d5621c59207
https://www.findamasters.com/masters-degrees/course/accounting-msc/?i13d8006c32505
https://www.findamasters.com/masters-degrees/course/accounting-and-finance-msc/?i366d5383c45563
https://www.findamasters.com/masters-degrees/course/accounting-acca-msc-pgcert-pgdip/?i286d3443c37949
https://www.findamasters.com/masters-degrees/course/accounting-and-analytics-ms/?i693d7481c44169
https://www.findamasters.com/masters-degrees/course/accounting-and-banking-msc/?i13d8006c32506
https://www.findamasters.com/masters-degrees/course/accounting-and-business-intelligence-msc/?i28d8299c69600
https://www.findamasters.com/masters-degrees/course/accounting-and-business-management-msc/?i28d2737c28531
https://www.findamasters.co

https://www.findamasters.com/masters-degrees/course/advanced-architectural-design-msc/?i177d852c52298
https://www.findamasters.com/masters-degrees/course/advanced-assessment-and-outcome-measures-practice-msc-pg-dip-pg-cert/?i391d7548c71106
https://www.findamasters.com/masters-degrees/course/advanced-audiology-msc/?i274d5870c19957
https://www.findamasters.com/masters-degrees/course/advanced-audiology-audiovestibular-medicine-msc/?i274d5870c59484
https://www.findamasters.com/masters-degrees/course/advanced-audiology-otology-and-skull-base-surgery-msc/?i274d5870c59485
https://www.findamasters.com/masters-degrees/course/advanced-biochemistry-msc/?i353d4190c47155
https://www.findamasters.com/masters-degrees/course/advanced-biological-sciences-msc/?i302d8969c67090
https://www.findamasters.com/masters-degrees/course/advanced-biomedical-engineering-msc/?i285d7565c52839
https://www.findamasters.com/masters-degrees/course/advanced-biomedical-imaging-msc/?i274d1817c37389
https://www.findamasters.

https://www.findamasters.com/masters-degrees/course/advanced-clinical-practice-primary-care-msc-pgdip/?i231d4343c71404
https://www.findamasters.com/masters-degrees/course/advanced-clinical-practice-radiography-msc/?i285d7561c71580
https://www.findamasters.com/masters-degrees/course/advanced-clinical-practice-with-v300-non-medical-prescribing-msc/?i373d172c71425
https://www.findamasters.com/masters-degrees/course/advanced-clinical-practice-in-ocular-health-msc/?i11d4266c68713
https://www.findamasters.com/masters-degrees/course/advanced-clinical-practice-in-ophthalmology-integrated-degree-apprenticeship-msc/?i274d1871c69803
https://www.findamasters.com/masters-degrees/course/advanced-clinical-practice-msc/?i49d2697c47525
https://www.findamasters.com/masters-degrees/course/advanced-clinical-practice-msc/?i228d1972c10932
https://www.findamasters.com/masters-degrees/course/advanced-clinical-practice-msc/?i374d6033c49094
https://www.findamasters.com/masters-degrees/course/advanced-clinical-p

https://www.findamasters.com/masters-degrees/course/advanced-functional-materials-msc/?i307d4813c21348
https://www.findamasters.com/masters-degrees/course/advanced-gis-and-remote-sensing-msc/?i50d6726c884
https://www.findamasters.com/masters-degrees/course/advanced-health-and-care-management-innovation-and-transformation-msc/?i231d239c64869
https://www.findamasters.com/masters-degrees/course/advanced-health-and-care-management-value-based-msc/?i231d239c64870
https://www.findamasters.com/masters-degrees/course/advanced-healthcare-practice-msc/?i33d4736c67062
https://www.findamasters.com/masters-degrees/course/advanced-healthcare-practice-msc/?i324d4570c58606
https://www.findamasters.com/masters-degrees/course/advanced-healthcare-practice-msc/?i147d2373c11714
https://www.findamasters.com/masters-degrees/course/advanced-hearing-therapy-practice-msc/?i11d4266c55113
https://www.findamasters.com/masters-degrees/course/advanced-hems-practice/?i13d8007c62091
https://www.findamasters.com/master

https://www.findamasters.com/masters-degrees/course/advanced-nurse-practitioner-professional-practice-msc/?i255d8458c49755
https://www.findamasters.com/masters-degrees/course/advanced-nursing-online-learning/?i300d5068c66656
https://www.findamasters.com/masters-degrees/course/advanced-nursing-msc-pgdip/?i338d6587c26372
https://www.findamasters.com/masters-degrees/course/advanced-nursing-practice-pgdip-pgcert-msc/?i188d7332c41336
https://www.findamasters.com/masters-degrees/course/advanced-nursing-science-msc/?i307d4814c47527
https://www.findamasters.com/masters-degrees/course/advanced-occupational-therapy-msc/?i337d1774c45042
https://www.findamasters.com/masters-degrees/course/advanced-occupational-therapy-msc-pgcert-pgdip/?i286d1653c56542
https://www.findamasters.com/masters-degrees/course/advanced-paramedic-practice-msc/?i313d1159c61840
https://www.findamasters.com/masters-degrees/course/advanced-pharmaceutical-manufacturing-msc/?i353d4190c29173
https://www.findamasters.com/masters-d

https://www.findamasters.com/masters-degrees/course/aerospace-engineering-and-management-msc/?i307d4813c21355
https://www.findamasters.com/masters-degrees/course/aerospace-engineering-msc/?i133d2455c8565
https://www.findamasters.com/masters-degrees/course/aerospace-engineering-with-advanced-practice-msc/?i235d416c54675
https://www.findamasters.com/masters-degrees/course/aerospace-engineering-msc/?i28d8287c4975
https://www.findamasters.com/masters-degrees/course/aerospace-engineering-msc/?i49d2694c28580
https://www.findamasters.com/masters-degrees/course/aerospace-engineering-msc/?i231d244c11247
https://www.findamasters.com/masters-degrees/course/aerospace-engineering-msc/?i235d416c54674
https://www.findamasters.com/masters-degrees/course/aerospace-engineering-msc-by-research/?i231d8819c32541
https://www.findamasters.com/masters-degrees/course/aerospace-engineering-sciences-master-of-science-ms/?i512d8310c68340
https://www.findamasters.com/masters-degrees/course/aerospace-manufacturing-

https://www.findamasters.com/masters-degrees/course/animal-welfare-and-conservation-msc/?i389d4350c20550
https://www.findamasters.com/masters-degrees/course/animal-welfare-msc/?i292d1883c56503
https://www.findamasters.com/masters-degrees/course/animal-welfare-science-ethics-and-law-msc/?i307d4814c22413
https://www.findamasters.com/masters-degrees/course/animate-materials-msc-by-research/?i67d1408c70969
https://www.findamasters.com/masters-degrees/course/anthropology-and-development-msc/?i150d2341c10504
https://www.findamasters.com/masters-degrees/course/anthropology-and-professional-practice-msc/?i274d1852c70249
https://www.findamasters.com/masters-degrees/course/anthropology-of-childhood-youth-and-education-msc/?i28d2862c17466
https://www.findamasters.com/masters-degrees/course/anthropology-of-international-development-and-humanitarian-assistance-msc/?i28d2862c28821
https://www.findamasters.com/masters-degrees/course/anthropology-environment-and-development-msc/?i274d1852c20137
https:

https://www.findamasters.com/masters-degrees/course/applied-image-and-signal-processing/?i1083d7708c49493
https://www.findamasters.com/masters-degrees/course/applied-infectious-disease-epidemiology-msc/?i274d5871c54962
https://www.findamasters.com/masters-degrees/course/applied-informatics/?i385d6809c70562
https://www.findamasters.com/masters-degrees/course/applied-informatics/?i3104d8161c56548
https://www.findamasters.com/masters-degrees/course/applied-informatics-msc/?i842d6573c29464
https://www.findamasters.com/masters-degrees/course/applied-innovation-design-msc/?i13d8008c63674
https://www.findamasters.com/masters-degrees/course/applied-instrumentation-and-control-msc/?i93d2645c2013
https://www.findamasters.com/masters-degrees/course/applied-international-development/?i345d711c42197
https://www.findamasters.com/masters-degrees/course/applied-linguistics-msc/?i300d1352c3747
https://www.findamasters.com/masters-degrees/course/applied-machine-learning-msc/?i112d2565c61098
https://www.

https://www.findamasters.com/masters-degrees/course/applied-statistics-in-health-sciences-on-campus-msc/?i353d6511c42901
https://www.findamasters.com/masters-degrees/course/applied-statistics-in-health-sciences-online-msc/?i353d6511c65305
https://www.findamasters.com/masters-degrees/course/applied-statistics-ms/?i693d7481c44171
https://www.findamasters.com/masters-degrees/course/applied-statistics-msc/?i349d6917c4002
https://www.findamasters.com/masters-degrees/course/applied-statistics-msc-pgdip/?i166d5300c30922
https://www.findamasters.com/masters-degrees/course/applied-statistics-with-data-science-online-msc/?i353d6511c65073
https://www.findamasters.com/masters-degrees/course/applied-transfusion-and-transplantation-science-msc/?i359d5894c68499
https://www.findamasters.com/masters-degrees/course/applied-translation-and-interpreting-msc-pgdip/?i353d445c42426
https://www.findamasters.com/masters-degrees/course/aquaculture-and-marine-resource-management-msc/?i883d5909c20466
https://www.

https://www.findamasters.com/masters-degrees/course/artificial-intelligence-with-speech-and-multimodal-interaction-msc-pgdip/?i106d4400c35467
https://www.findamasters.com/masters-degrees/course/artificial-intelligence-online-msc/?i280d8352c60065
https://www.findamasters.com/masters-degrees/course/arts-and-creative-technologies-by-negotiated-study-full-time-ma-msc/?i228d1970c7994
https://www.findamasters.com/masters-degrees/course/arts-and-creative-technologies-by-negotiated-study-part-time-ma-msc/?i228d1970c44624
https://www.findamasters.com/masters-degrees/course/asset-management-with-digital-technologies/?i298d3331c67176
https://www.findamasters.com/masters-degrees/course/astrobiology-msc/?i16d9015c70436
https://www.findamasters.com/masters-degrees/course/astrobiology-and-planetary-sciences-msc/?i300d3320c70697
https://www.findamasters.com/masters-degrees/course/astronautics-and-space-engineering-msc/?i50d4274c532
https://www.findamasters.com/masters-degrees/course/astronomy-msc/?i35

ConnectionError: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/msc-degrees/?PG=101 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD77AB7610>: Failed to establish a new connection: [WinError 10065] Une opération a été tentée sur un hôte impossible à atteindre'))

In [3]:
#Saving the collected URL's in a txt file
with open('url.txt', 'w') as file:
    # Write each URL to a new line
    for url in data:
        file.write(url + '\n')

### 1.2. Crawl master's degree pages

In [4]:
#Saving the .txt folder as a list
with open('url.txt', 'r') as file:
    # Read the file line by line
    urls = [line.strip() for line in file]

In [6]:
import os
import requests
from urllib.parse import urlparse
from bs4 import BeautifulSoup

def download_and_save_html(url, folder_path, page_number):
    try:
        response = requests.get(url)
        time.sleep(5)
        if response.status_code == 200:
            # Parse the URL to extract the hostname for folder naming
            parsed_url = urlparse(url)
            hostname = parsed_url.netloc.replace('.', '_')

            # Calculate the page number based on 15 links per page
            folder_number = (page_number - 1) // 15 + 1

            # Create a folder for each page number
            folder_name = os.path.join(folder_path, f'Page_{folder_number}', hostname)
            os.makedirs(folder_name, exist_ok=True)

            # Save the HTML content to a file
            file_name = os.path.join(folder_name, f'index_{page_number % 15}.html')
            with open(file_name, 'w', encoding='utf-8') as f:
                f.write(response.text)
            print(f"HTML saved for {url}")
        else:
            print(f"Failed to download HTML for {url}. Status code: {response.status_code}")
    except Exception as e:
        print(f"An error occurred while downloading {url}: {e}")

def download_html_links_from_file(file_path, output_folder):
    with open(file_path, 'r', encoding='utf-8') as file:
        urls = file.read().splitlines()

    for i, url in enumerate(urls, start=1):
        download_and_save_html(url, output_folder, i)

# Example usage:
txt_file_path = 'url.txt'  # Replace with the path to your text file containing URLs
output_folder_path = 'Download_html'  # Replace with the desired output folder path

download_html_links_from_file(txt_file_path, output_folder_path)

HTML saved for https://www.findamasters.com/masters-degrees/course/3d-design-for-virtual-environments-msc/?i93d2645c19223
HTML saved for https://www.findamasters.com/masters-degrees/course/accounting-and-finance-msc/?i321d3232c3891
HTML saved for https://www.findamasters.com/masters-degrees/course/accounting-and-finance-msc/?i280d4409c4025
HTML saved for https://www.findamasters.com/masters-degrees/course/accounting-accountability-and-financial-management-msc/?i132d7816c25522
HTML saved for https://www.findamasters.com/masters-degrees/course/accounting-financial-management-and-digital-business-msc/?i345d4286c351
HTML saved for https://www.findamasters.com/masters-degrees/course/actuarial-management-msc/?i393d8527c62946
HTML saved for https://www.findamasters.com/masters-degrees/course/actuarial-science-msc/?i393d8527c62945
HTML saved for https://www.findamasters.com/masters-degrees/course/addictions-msc/?i132d4318c27100
HTML saved for https://www.findamasters.com/masters-degrees/course

HTML saved for https://www.findamasters.com/masters-degrees/course/city-planning-and-real-estate-development-msc/?i307d4959c29455
HTML saved for https://www.findamasters.com/masters-degrees/course/civil-engineering-msc/?i309d3273c63708
HTML saved for https://www.findamasters.com/masters-degrees/course/civil-engineering-structures-msc/?i393d8904c457
HTML saved for https://www.findamasters.com/masters-degrees/course/climate-change-management-and-finance-msc/?i112d3962c40746
HTML saved for https://www.findamasters.com/masters-degrees/course/climate-futures-science-society-and-politics-msc/?i321d1015c69355
HTML saved for https://www.findamasters.com/masters-degrees/course/clinical-neuroscience-msc/?i201d425c964
HTML saved for https://www.findamasters.com/masters-degrees/course/clinical-nursing-msc-online/?i132d2469c17654
HTML saved for https://www.findamasters.com/masters-degrees/course/clinical-optometry-msc/?i393d8906c27785
HTML saved for https://www.findamasters.com/masters-degrees/cour

HTML saved for https://www.findamasters.com/masters-degrees/course/economics-msc/?i393d4030c22135
HTML saved for https://www.findamasters.com/masters-degrees/course/economics-of-markets-and-organisations-msc/?i2814d7765c50618
HTML saved for https://www.findamasters.com/masters-degrees/course/economics-of-sustainability-msc/?i2814d7765c66156
HTML saved for https://www.findamasters.com/masters-degrees/course/education-msc-online/?i307d4959c54938
HTML saved for https://www.findamasters.com/masters-degrees/course/education-for-sustainable-futures-in-adult-community-and-youth-contexts-msc/?i307d4959c49111
HTML saved for https://www.findamasters.com/masters-degrees/course/education-public-policy-and-equity-msc/?i307d4959c43673
HTML saved for https://www.findamasters.com/masters-degrees/course/emerging-economies-and-international-development-msc/?i132d2510c27532
HTML saved for https://www.findamasters.com/masters-degrees/course/energy-and-environment-msc/?i321d8433c12303
HTML saved for https:

An error occurred while downloading https://www.findamasters.com/masters-degrees/course/geographical-information-science-msc/?i321d1022c3600: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/geographical-information-science-msc/?i321d1022c3600 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
An error occurred while downloading https://www.findamasters.com/masters-degrees/course/geospatial-data-science-and-modelling-msc/?i307d4813c72073: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/geospatial-data-science-and-modelling-msc/?i307d4813c72073 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD767352D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while downloading https://www.findamasters.com/mas

An error occurred while downloading https://www.findamasters.com/masters-degrees/course/msc-engineering-for-marine-professionals-top-up/?i2308d7409c52395: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/msc-engineering-for-marine-professionals-top-up/?i2308d7409c52395 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD76702250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while downloading https://www.findamasters.com/masters-degrees/course/msc-engineering-management/?i315d8200c56797: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/msc-engineering-management/?i315d8200c56797 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD78ED7F50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while down

An error occurred while downloading https://www.findamasters.com/masters-degrees/course/strategy-economics-msc/?i2814d7765c50621: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/strategy-economics-msc/?i2814d7765c50621 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD767036D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while downloading https://www.findamasters.com/masters-degrees/course/stroke-medicine-msc/?i1705d6873c69080: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/stroke-medicine-msc/?i1705d6873c69080 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD76703810>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while downloading https://www.findamasters.com/masters-degrees/course/st

An error occurred while downloading https://www.findamasters.com/masters-degrees/course/advanced-clinical-practice-msc-pgdip/?i224d4983c61850: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/advanced-clinical-practice-msc-pgdip/?i224d4983c61850 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD76703050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while downloading https://www.findamasters.com/masters-degrees/course/advanced-clinical-practice-msc-pgdip/?i166d8739c71342: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/advanced-clinical-practice-msc-pgdip/?i166d8739c71342 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD73701090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while download

An error occurred while downloading https://www.findamasters.com/masters-degrees/course/aerodynamics-and-computation-msc/?i349d6709c7089: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/aerodynamics-and-computation-msc/?i349d6709c7089 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD76702090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while downloading https://www.findamasters.com/masters-degrees/course/aeronautical-engineering/?i811d6071c27545: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/aeronautical-engineering/?i811d6071c27545 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD76703210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while downloading https://www.findamasters.com/m

An error occurred while downloading https://www.findamasters.com/masters-degrees/course/applied-meteorology-and-climatology-msc/?i282d4303c4066: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/applied-meteorology-and-climatology-msc/?i282d4303c4066 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD76702D10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while downloading https://www.findamasters.com/masters-degrees/course/applied-microbiology-and-biotechnology-msc/?i373d8428c29278: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/applied-microbiology-and-biotechnology-msc/?i373d8428c29278 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD767036D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurre

An error occurred while downloading https://www.findamasters.com/masters-degrees/course/banking-and-digital-finance-msc/?i274d1826c55672: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/banking-and-digital-finance-msc/?i274d1826c55672 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD76702090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while downloading https://www.findamasters.com/masters-degrees/course/banking-and-finance-msc/?i13d8006c53539: HTTPSConnectionPool(host='www.findamasters.com', port=443): Max retries exceeded with url: /masters-degrees/course/banking-and-finance-msc/?i13d8006c53539 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DD76700B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
An error occurred while downloading https://www.findamasters.com/maste

### 1.3 Parse downloaded pages

In [7]:
column_names = ["courseName",
                "universityName",
                "facultyName",
                "isItFullTime",
                "description",
                "startDate",
                "fees",
                "modality",
                "duration",
                "city",
                "country",
                "administration",
                "url"]

In [8]:
#Creating a Data Frame with the required columns
df = pd.DataFrame(columns = column_names)
print(df)


Empty DataFrame
Columns: [courseName, universityName, facultyName, isItFullTime, description, startDate, fees, modality, duration, city, country, administration, url]
Index: []


In [10]:
#Collecting the data from each HTML file and add it to the Data Frame

print(df)
#looping through each file of the folder
for i in range(1, 401):
    folder_name = f'Download_html\Page_{i}\www_findamasters_com'
    print(folder_name)
    for j in range(15):
        file_name = f'index_{j}.html'
        print(os.path.join(folder_name, file_name))

        with open(os.path.join(folder_name, file_name), 'r', encoding='utf-8') as f:
            contents = f.read()
            soup = BeautifulSoup(contents, 'html.parser')

        try:
            courseName = soup.find("h1", {"class": "course-header__course-title"}).text
        except:
            courseName = ""

        try:
            universityName = soup.find('a', {'class': 'course-header__institution'}).text
        except:
            universityName = ""

        try:
            facultyName = soup.find('a', {'class': 'course-header__department'}).text
        except:
            facultyName = ""

        try:
            FullTime_links= soup.find_all('a', {'class':'concealLink' })
            FullTime = False
            for item in FullTime_links:
                if item['href']== "/masters-degrees/full-time/":
                    FullTime = True
                    break
            isItFullTime= FullTime
        except:
            isItFullTime= False

        try:
            paragraphs = soup.find("div", class_="course-sections course-sections__description col-xs-24")
            paragraphs = paragraphs.find("div", id="Snippet").find_all("p")
            description = " ".join([paragraph.text.strip() for paragraph in paragraphs])
        except:
            description = ""

        try:
            startDate = soup.find("span", {"class": "key-info__start-date"}).text
        except:
            startDate = ""

        try:
            fees = soup.find("div", class_="course-sections course-sections__fees tight col-xs-24")
            fees = fees.find("div", class_="course-sections__content").find("p").text
        except:
            fees = ""

        try:
            modality = soup.find("span", {"class": "key-info__qualification"}).text
        except:
            modality = ""

        try:
            duration = soup.find("span", {"class": "key-info__duration"}).text
        except:
            duration = ""

        try:
            city = soup.find("a", {"class": "card-badge text-wrap text-left badge badge-gray-200 p-2 m-1 font-weight-light course-data course-data__city"}).text
        except:
            city= ""

        try:
            country = soup.find("a", {"class": "card-badge text-wrap text-left badge badge-gray-200 p-2 m-1 font-weight-light course-data course-data__country"}).text
        except:
            country = ""

        online_course = soup.find("a", {"class": "course-data__online"})
        on_campus_course = soup.find("a", {"class": "course-data__on-campus"})
        if online_course is None and on_campus_course is None:
            administration = ""
        elif online_course is None:
            administration = on_campus_course.text
        elif on_campus_course is None:
            administration = online_course.text
        else:
            administration = online_course.text + ', ' + on_campus_course.text

        url = soup.find("link", rel="canonical")["href"]

        data = {"courseName": courseName,
                "universityName": universityName,
                "facultyName": facultyName,
                "isItFullTime": isItFullTime,
                "description": description,
                "startDate": startDate,
                "fees": fees,
                "modality": modality,
                "duration": duration,
                "city": city,
                "country": country,
                "administration": administration,
                "url": url}
        print(data)

        df = pd.DataFrame(columns=column_names)
        df = pd.concat([df, pd.DataFrame([data], columns=df.columns)], ignore_index=True)
        df.to_csv(f"courses/course_{((i-1)*15) +j}.tsv", sep="\t", index=False)
        #df.append(data, ignore_index=True)

                      courseName       universityName  \
0    Air Quality Solutions - MSc  University of Leeds   

                       facultyName isItFullTime  \
0  Institute for Transport Studies         True   

                                         description  startDate  \
0  Up to 7 million people are estimated to die ev...  September   

                                                fees modality  \
0  UK: £12,500 (Total) International: £28,750 (To...      MSc   

                                   duration   city         country  \
0  1 year full time, 2 or 3 years part-time  Leeds  United Kingdom   

  administration                                                url  
0      On Campus  https://www.findamasters.com/masters-degrees/c...  
Download_html\Page_1\www_findamasters_com
Download_html\Page_1\www_findamasters_com\index_0.html
{'courseName': '\xa0\xa0Air Quality Solutions - MSc', 'universityName': 'University of Leeds', 'facultyName': 'Institute for Transport Stu

{'courseName': '\xa0\xa0Actuarial Science MSc', 'universityName': 'City, University of London', 'facultyName': 'Faculty of Actuarial Science and Insurance', 'isItFullTime': True, 'description': 'The MSc in Actuarial Science will prepare you for a high-flying career as an actuary in traditional and non-traditional actuarial fields. You also have the option to choose the Business Analytics pathway which will provide you with the much sought after skills in this area. If you have strong technical ability and an interest in solving business problems, becoming an actuary is one of the most rewarding career choices you can make. Changes in the world bring new risks, which mean new challenges for actuaries.', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '1 year full time', 'city': 'London', 'country': 'United Kingdom', 'administration': 'On Campus', 'url': 'https://www.findamasters.com/ma

{'courseName': '\xa0\xa0Advanced Physiotherapy Practice - MSc', 'universityName': 'Glasgow Caledonian University', 'facultyName': 'School of Health and Life Sciences', 'isItFullTime': True, 'description': 'Progress your career as a physiotherapist within the NHS, private sector and in other health and social care settings. Take existing skills in health and social care and apply them to research, clinical assessment, analysis and insight. Learn in state-of-the-art facilities, study the latest in clinical research and get leading-edge training in our MSc Physiotherapy course. GCU collaborates with industry to bring a cutting-edge course of study to physiotherapists seeking to advance their careers. The course is delivered by practising experts, specialists and academics – and informed by the latest developments in the field.', 'startDate': 'January, September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '1

{'courseName': '\xa0\xa0Applied Linguistics - MSc', 'universityName': 'University of Glasgow', 'facultyName': 'College of Arts & Humanities', 'isItFullTime': True, 'description': 'This Masters focuses on how linguistic research can help solve language-related problems in professional practice and public life. It is designed for you to become a research-led specialist in areas such as language and education, intercultural communication, language and politics and professional discourse. You will design and undertake your own applied research project as part of this', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '1 year full-time; 2 years part-time', 'city': 'Glasgow', 'country': 'United Kingdom', 'administration': 'On Campus', 'url': 'https://www.findamasters.com/masters-degrees/course/applied-linguistics-msc/?i307d4953c55536'}
Download_html\Page_2\www_findamasters_com\index_8.html
{

{'courseName': '\xa0\xa0Biopharmaceutical Development (Industrial Placement) - MSc', 'universityName': 'University of Leeds', 'facultyName': 'School of Molecular and Cellular Biology', 'isItFullTime': True, 'description': 'Be at the cutting edge of modern medicine, gain invaluable experience, make essential connections, and be paid for your efforts. This Biopharmaceutical Development with Industrial Placement Masters is your opportunity to develop and build the necessary skill-set needed to flourish within the field of biopharmaceutical discovery & development. What better way to start your career than with a paid 12-month placement, earning up to £20,000 whilst working with an industry leading', 'startDate': 'September', 'fees': 'UK: £24,500 (Total) International: £37,000 (Total)', 'modality': 'MSc', 'duration': '20 months full time, 48 months part time', 'city': 'Leeds', 'country': 'United Kingdom', 'administration': 'On Campus', 'url': 'https://www.findamasters.com/masters-degrees/c

{'courseName': '\xa0\xa0Banking and International Finance - MSc', 'universityName': 'University of Leeds', 'facultyName': 'Leeds University Business School', 'isItFullTime': True, 'description': "Integrated financial markets and global businesses contribute significantly to modern banking, which is inseparable from international finance. This course provides you with a comprehensive overview of central issues in banking and international finance. You’ll acquire an understanding of the forces that sway financial markets as well as the theories underlying commercial and international banking. You'll gain knowledge and skills that can be practically applied which you'll put to the test in real-life scenarios through practical exercises.", 'startDate': 'September', 'fees': 'UK: £18,000 (Total) International: £34,750 (Total)', 'modality': 'MSc', 'duration': '1 year full time', 'city': 'Leeds', 'country': 'United Kingdom', 'administration': 'On Campus', 'url': 'https://www.findamasters.com/m

{'courseName': '\xa0\xa0Business in Technology MSc', 'universityName': 'Ulster University', 'facultyName': 'Ulster Online', 'isItFullTime': False, 'description': 'Our 100% online Business in Technology programme is a unique MBA-style Masters designed to equip you with the specialist management skills needed to become an effective leader across a range of tech-led industries. Study part-time and work towards a qualification that aligns with your professional and personal goals, at a pace that suits you. The programme can be split into three pathways, allowing you to graduate sooner with a PG Cert (8 months minimum), PG Dip (16 months) or continue to gain a full Masters qualification in two years part-time.', 'startDate': 'September, November', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc, PGDip, PGCert', 'duration': '2-4 years', 'city': 'Coleraine', 'country': 'United Kingdom', 'administration': 'Online', 'url': 'https://

{'courseName': '\xa0\xa0Business Analytics (MSc)', 'universityName': 'University of Bath', 'facultyName': 'School of Management', 'isItFullTime': True, 'description': 'Develop your understanding of business analytics. You’ll graduate with the skills you need to start a career specialising in data and decision analysis. This course is for graduates who want to pursue a career in business analytics. How can companies use ‘big data’ to gain business insight? This course will teach you how to convert data into knowledge. Get hands-on practical experience using the latest business intelligence software and interpreting real data. This course includes guest lectures from industry experts, and a unit co-delivered by a specialist from IBM. In partnership with IBM, Qlik, WinPure and\xa0the Women in OR & Analytics Network.', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '1 year full-time', 'c

{'courseName': '\xa0\xa0Clinical Neuroscience - MSc', 'universityName': 'University of Roehampton', 'facultyName': 'School of Life and Health Sciences', 'isItFullTime': True, 'description': 'This cutting-edge MSc Clinical Neuroscience offers an exciting opportunity to study modern neuroscience with a focus on clinical implications. Gain a strong foundation in understanding the mechanisms and treatments of neurological and neuropsychiatric diseases. This programme is designed for students from a range of backgrounds, who are interested in pursuing a career in neuroscience. You will develop a detailed understanding of modern theory and concepts relating to brain research and neuroscience and the application of these principles in the treatment of brain disorders. This course places emphasis on the clinical relevance of recent developments in neuroscience.', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 

{'courseName': '\xa0\xa0China & Globalisation MSc', 'universityName': 'King’s College London', 'facultyName': 'Faculty of Social Science & Public Policy', 'isItFullTime': True, 'description': 'Our China & Globalisation MSc provides an introduction to the causes and consequences of China’s rise from comparative and global perspectives. It will equip you with the conceptual and research tools necessary for the critical analysis of China’s social, political, and economic trends, and support your understanding of Chinese public policies, business strategies and modes of international cooperation. Visit our online hubs for content, news and events about the Lau China Institute', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '1 year FT; 2 years PT', 'city': 'London', 'country': 'United Kingdom', 'administration': 'On Campus', 'url': 'https://www.findamasters.com/masters-degrees/course/chi

{'courseName': '\xa0\xa0Clinical Nursing MSc (Online)', 'universityName': 'King’s College London', 'facultyName': 'Florence Nightingale Faculty of Nursing, Midwifery & Palliative Care', 'isItFullTime': False, 'description': 'Qualified nurses provide, lead and coordinate care, and high-quality nursing care is key to the success of patient recovery. Having the right mix of knowledge and skills is therefore hugely important to ensure the people you care for have positive clinical outcomes. This course supports qualified nurses to develop their knowledge and skills so they are able to take their career in nursing to the next level. The course will support you in your path to become an expert clinical decision-maker, able to autonomously manage and lead healthcare practice.', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': 'Part Time: 2 - 3 Years', 'city': 'London', 'country': 'United King

{'courseName': '\xa0\xa0Computational Geoscience - MSc', 'universityName': 'University of Glasgow', 'facultyName': 'College of Science and Engineering', 'isItFullTime': True, 'description': 'The Masters in Computational Geoscience explores how we model the natural world and the environment around us (and the processes that create them). You will develop applied data science and modelling skills which you can use to address complex real-world challenges and support decision-making in geoscience fields. You will develop skills that are in high-demand in the geoscience sector, including computer programming, predictive modelling and big data analysis.', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '1 year full-time, 2 years part-time', 'city': 'Glasgow', 'country': 'United Kingdom', 'administration': 'On Campus', 'url': 'https://www.findamasters.com/masters-degrees/course/computationa

{'courseName': '\xa0\xa0Construction Economics and Management MSc', 'universityName': 'University College London', 'facultyName': 'The Bartlett School of Construction Management', 'isItFullTime': True, 'description': "This programme equips graduates with the competencies to become policy advisors, consultants, senior managers and decision-makers in any branch of the construction and infrastructure industry. It can also provide researchers and teachers in these subject areas with professional academic development. The programme is accredited by the Royal Institution of Chartered Surveyors (RICS) and aims to develop students' knowledge and skills under two mutually supporting themes, for which The Bartlett School of Sustainable Construction has an international reputation:", 'startDate': 'September', 'fees': 'Full time - £21,200 Part time - £10,600', 'modality': 'MSc', 'duration': '1 year full time, 2 years part time, 5 years flexible', 'city': 'London', 'country': 'United Kingdom', 'adm

{'courseName': '\xa0\xa0Criminology and Criminal Justice MSc', 'universityName': 'City, University of London', 'facultyName': 'School of Policy and Global Affairs', 'isItFullTime': True, 'description': 'Investigate the human fascination with crime by taking a critical approach to criminology and criminal justice in this MSc programme. You may pursue an established field of learning or specialise in a subject area that relates to your background or career ambitions.', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '1 year full-time, 2 years part-time', 'city': 'London', 'country': 'United Kingdom', 'administration': 'On Campus', 'url': 'https://www.findamasters.com/masters-degrees/course/criminology-and-criminal-justice-msc/?i393d4030c11635'}
Download_html\Page_7\www_findamasters_com\index_10.html
{'courseName': '\xa0\xa0Cyber Security - MSc', 'universityName': 'Glasgow Caledonian Uni

{'courseName': '\xa0\xa0Data Analytics for Government - MSc/PgDip/PgCert (online)', 'universityName': 'University of Glasgow', 'facultyName': 'College of Science and Engineering', 'isItFullTime': False, 'description': 'While the amount of data being produced is proliferating at a staggering rate, the skills to extract information and the value we receive from it are both relatively scarce. Analytics and data-driven decisioning is playing an increasingly important role in the economy, society and public administration. Designed together with the Office for National Statistics, our MSc in Online Data Analytics for Government is based on our successful online MSc programme in Data Analytics and will provide you with vital skills required to develop your modelling and data handling expertise. You will gain a firm grounding in the principles of learning from data sets, whilst at the same time getting hands-on experience handling, analysing and visualising data, helping your organisation to 

{'courseName': '\xa0\xa0Diabetes Clinical Care and Management MSc (Online)', 'universityName': 'King’s College London', 'facultyName': 'Florence Nightingale Faculty of Nursing, Midwifery & Palliative Care', 'isItFullTime': False, 'description': 'Diabetes is a long-term condition affecting over 460 million adults worldwide, and its prevalence is predicted to increase to 700 million in 2045; posing further health and economic challenges', 'startDate': 'See Course', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '3 Years', 'city': 'London', 'country': 'United Kingdom', 'administration': 'Online', 'url': 'https://www.findamasters.com/masters-degrees/course/diabetes-clinical-care-and-management-msc-online/?i132d2469c68890'}
Download_html\Page_8\www_findamasters_com\index_9.html
{'courseName': '\xa0\xa0Digital Business and Data Analytics - MSc', 'universityName': 'University of Reading', 'facultyName': 'Henley Busi

{'courseName': '\xa0\xa0Digital Innovation - MSc', 'universityName': 'University of Reading', 'facultyName': 'Henley Business School', 'isItFullTime': True, 'description': 'This Masters degree will equip you with the knowledge, skills and tools to lead, manage, develop, and implement innovative digital business solutions. You will gain the frontier knowledge and skills required to manage digital technologies in the development and delivery of business innovations. Effective leadership requires more than first-class business acumen, it requires a degree of self-awareness and sensitivity. Our Masters programmes offer you a unique practice-centred approach to teaching equipping you with the tools to become a compelling leader. This approach creates emotionally intelligent graduates who can be fully effective in their chosen careers.', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '1 ye

{'courseName': '\xa0\xa0Diplomacy, International Business and Trade MSc', 'universityName': 'Loughborough University London', 'facultyName': 'Institute for Diplomacy and International Governance', 'isItFullTime': True, 'description': 'Our Diplomacy, International Business and Trade MSc provides an extensive overview of the practices of international business diplomacy. The challenges of trading in the global village, and the multiple communities and markets driving world commerce through new and old trade routes are dissected in this programme. You will learn in an environment tailor-made for the development of the skills needed to critically understand globalisation, as well as the knowledge of the current issues characterising relations between diplomacy, international business, and international trade.', 'startDate': 'September, January', 'fees': 'For more information, please visit the programme page on our website.', 'modality': 'MSc', 'duration': 'Full-time: 1 year, Part-time: up 

{'courseName': '\xa0\xa0Economics and Finance - MSc', 'universityName': 'University of Leeds', 'facultyName': 'Leeds University Business School', 'isItFullTime': True, 'description': 'This course provides an opportunity to combine an understanding of sophisticated economic theory with advanced finance concepts. You’ll study micro and macroeconomics and the methodology of econometric research, while exploring corporate finance and the financial economics tools commonly used in financial services, quantitative investment analysis and research. You’ll take an open-minded approach to economic problems, studying current mainstream theory and applied techniques alongside a range of alternative critical perspectives.', 'startDate': 'September', 'fees': 'UK: £15,000 (Total) International: £30,750 (Total)', 'modality': 'MSc', 'duration': '1 year full time', 'city': 'Leeds', 'country': 'United Kingdom', 'administration': 'On Campus', 'url': 'https://www.findamasters.com/masters-degrees/course/ec

{'courseName': '\xa0\xa0Education for Sustainable Futures in Adult, Community & Youth Contexts - MSc', 'universityName': 'University of Glasgow', 'facultyName': 'College of Social Sciences', 'isItFullTime': True, 'description': 'The Masters in Education for Sustainable Futures is an interdisciplinary, community-oriented, and impact-driven programme. It is designed to support you in developing practical and imaginative skills to create and foster sustainable futures through education. Focusing on education within adult, community, and youth settings, it takes a culturally responsive, and ecologically mindful approach to understanding and reimagining educational practices as they relate to the sustainability challenges and opportunities of our times, both locally and globally.', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '1 year full-time; 2 years part-time', 'city': 'Glasgow', 'co

{'courseName': '\xa0\xa0Energy, Environmental Technology and Economics MSc', 'universityName': 'City, University of London', 'facultyName': 'School of Science and Technology', 'isItFullTime': True, 'description': 'Affordable and clean energy is key to meeting the challenges of climate change and sustainable development. On this MSc you’ll gain an understanding of technologies for energy production, and the knowledge and vision required to deliver a sustainable future. This programme will open-up real-world career opportunities across the sector.', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '1 year full time, 2 years (up to 28 months) part time', 'city': 'London', 'country': 'United Kingdom', 'administration': 'On Campus', 'url': 'https://www.findamasters.com/masters-degrees/course/energy-environmental-technology-and-economics-msc/?i393d8904c461'}
Download_html\Page_11\www_findama

{'courseName': '\xa0\xa0Entrepreneurship Management and Innovation, online MSc', 'universityName': 'University of Bath', 'facultyName': 'University of Bath Online', 'isItFullTime': False, 'description': 'Join us for Entrepreneurship Management and Innovation online MSc course overview webinar led by course director, Dr Stoyan Stoyanov. Combine your own drive and ambition with the academic excellence and insights provided by the University of Bath’s Entrepreneurship Management and Innovation online MSc. Delivered by the EQUIS- and ABMA-accredited Bath School of Management, this online postgraduate course provides exciting new perspectives on traditional business disciplines, setting in motion a journey of lifelong enterprise. Whether you’re expanding a family business, carving out a new enterprise or seeking to make a positive impact from within your corporation, our world-leading school will help to take you there.', 'startDate': 'September, January', 'fees': 'Cost per 10 credits £833*

{'courseName': '\xa0\xa0Environmental, Social, Governance (ESG) Management MSc', 'universityName': 'King’s College London', 'facultyName': 'King’s Business School', 'isItFullTime': True, 'description': 'More than ever ESG is essential for businesses and organisations. Climate concerns, sustainability & corporate responsibility are at the forefront of the way organisations do business, and it is pivotal for businesses to adapt to these new challenges. ESG Managers need to understand the nuances of these areas, and strategise accordingly to help organisations navigate these risks & opportunities. Our ESG Management MSc will introduce you to cutting-edge theoretical and applied research on the management of environmental, social, and governance matters. The topic areas covered are multi-disciplinary, and the programme will offer you research and problem-based perspectives from fields as diverse as science, economics, accounting, finance, law, and strategy.', 'startDate': 'September', 'fee

{'courseName': '\xa0\xa0Finance - MSc', 'universityName': 'Trinity College Dublin', 'facultyName': 'Trinity Business School', 'isItFullTime': True, 'description': 'Ranked 2nd in Western Europe for Corporate Finance (Eduniversal 2018), this programme is designed to help students develop the skills they need to excel in their chosen career within finance. Highly interactive lessons will provoke discussion and provide opportunities to develop presentation skills, deal with real-life case studies and work in group assignments. Ranked 21st in the world and 1st in Ireland in the Masters in Finance category - Times Higher Education/Wall Street Journal Rankings, 2018. 92% rate of employment post-graduation.*', 'startDate': 'September', 'fees': 'Please see the university website for further information on fees for this course.', 'modality': 'MSc', 'duration': '1 year full-time', 'city': 'Dublin', 'country': 'Ireland', 'administration': 'On Campus', 'url': 'https://www.findamasters.com/masters-d

FileNotFoundError: [Errno 2] No such file or directory: 'Download_html\\Page_13\\www_findamasters_com\\index_0.html'

## 2.Search Engine

### 2.0 Preprocessing

#### 2.0.0 Preprocessing the text

Let's first check the data we collected previously in our csv file.

In [12]:
dataset = pd.read_csv("./merged_courses.tsv", delimiter="\t")

In [13]:
dataset.head()

courseName  \
0        3D Design for Virtual Environments - MSc   
1                    Accounting and Finance - MSc   
2                       Analytical Toxicology MSc   
3             Entrepreneurship & Innovation - MSc   
4    Amputation and Prosthetic Rehabilitation MSc   

                  universityName                                  facultyName  \
0  Glasgow Caledonian University  School of Engineering and Built Environment   
1            University of Leeds             Leeds University Business School   
2          King’s College London          Faculty of Life Sciences & Medicine   
3         Trinity College Dublin                      Trinity Business School   
4      University of Southampton   Faculty of Environmental and Life Sciences   

   isItFullTime                                        description  \
0          True  3D visualisation and animation play a role in ...   
1          True  Businesses and governments rely on sound finan...   
2          True  The Analytical Toxicology MSc is a unique stud...   
3          True  This programme is designed to equip students w...   
4          True  Enhance your practice at a global top 100* uni...   

    startDate                                               fees modality  \
0   September  Please see the university website for further ...      MSc   
1   September  UK: £18,000 (Total) International: £34,750 (To...      MSc   
2  See Course  Please see the university website for further ...      MSc   
3   September  Please see the university website for further ...      MSc   
4   September  Please see the university website for further ...      MSc   

                                 duration         city         country  \
0                        1 year full-time      Glasgow  United Kingdom   
1                        1 year full time        Leeds  United Kingdom   
2                     Full-time: One year       London  United Kingdom   
3                        1 year full-time       Dublin         Ireland   
4  1 Year Full Time / 2-4 Years Part Time  Southampton  United Kingdom   

  administration                                                url  
0      On Campus  https://www.findamasters.com/masters-degrees/c...  
1      On Campus  https://www.findamasters.com/masters-degrees/c...  
2      On Campus  https://www.findamasters.com/masters-degrees/c...  
3      On Campus  https://www.findamasters.com/masters-degrees/c...  
4      On Campus  https://www.findamasters.com/masters-degrees/c...

##### Stemming with NLTK

In [14]:
#let's use the NLTK library for stemming :
from nltk.stem import *

In [15]:
#we remove here all the empty string descriptions
dataset = dataset[dataset.description != '']

In [16]:
dataset = dataset.dropna(subset=['description'])

In [17]:
# Replace '\n' with a space or empty string as you prefer
dataset['description'] = dataset['description'].str.replace('\n', ' ', regex=False)
dataset.description.head()

0    3D visualisation and animation play a role in ...
1    Businesses and governments rely on sound finan...
2    The Analytical Toxicology MSc is a unique stud...
3    This programme is designed to equip students w...
4    Enhance your practice at a global top 100* uni...
Name: description, dtype: object

##### Port Stemmer

Let's now use another common method for stemming, Porter Stemmer:

In [18]:
porterstemmer = PorterStemmer()

#descr_stem stands here for the new stemmed column
dataset['descr_stem'] = dataset.description.apply(lambda row: [porterstemmer.stem(word) for word in row.split(' ')])

We can see how the list created by splitting and stemming the description column of the 1st row looks like:

In [19]:
lst_porter = [porterstemmer.stem(word) for word in dataset.loc[0,'description'].split(' ')]
lst_porter

['3d',
 'visualis',
 'and',
 'anim',
 'play',
 'a',
 'role',
 'in',
 'mani',
 'areas,',
 'and',
 'the',
 'popular',
 'of',
 'these',
 'media',
 'just',
 'keep',
 'growing.',
 'digit',
 'anim',
 'provid',
 'the',
 'eye-catch',
 'special',
 'effect',
 'in',
 'the',
 '21st',
 "century'",
 'favourit',
 'film',
 'and',
 'televis',
 'shows;',
 '3d',
 'design',
 'is',
 'also',
 'essenti',
 'to',
 'everyday',
 'work',
 'in',
 'everyth',
 'from',
 'comput',
 'game',
 'development,',
 'onlin',
 'virtual',
 'world',
 'develop',
 'and',
 'industri',
 'design',
 'to',
 'marketing,',
 'product',
 'design',
 'and',
 'architecture.',
 "gcu'",
 'programm',
 'in',
 '3d',
 'design',
 'for',
 'virtual',
 'environ',
 'will',
 'help',
 'you',
 'develop',
 'the',
 'skill',
 'to',
 'thrive',
 'in',
 'a',
 'success',
 'career',
 'as',
 'a',
 'visual',
 'designer.',
 'the',
 'programm',
 'is',
 'practic',
 'and',
 'career-focused,',
 'orient',
 'toward',
 'current',
 'industri',
 'needs,',
 'technolog',
 'and',

#### Removing StopWords with NLTK

To develop a search engine, it is essential to eliminate certain words that lack substantial information and are redundantly used, commonly known as stop words.

In [20]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rochd\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [46]:
lst_stopwords = stopwords.words('english')

In this context, let's examine the complete list of stopwords available in the NLTK library:

In [47]:
lst_stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

As evident, words like 'I,' 'him,' 'wouldn't,' etc., are irrelevant and may disrupt our search results.

Now, we have the option to introduce an additional column into the dataset, labeled 'descr_clean,' which exclusively incorporates the stemmed words not present in the stopwords list:

In [23]:
dataset['descr_clean'] = dataset.description.apply(lambda row: [porterstemmer.stem(word) for word in row.split(' ') if not word in lst_stopwords])

Take a brief comparison at the distinction between the two appended columns:

"descr_stem" includes the stemmed version of all words.
Meanwhile, "descr_clean" excludes stopwords.

In [24]:
dataset.loc[0, ['descr_clean', 'descr_stem']]

descr_clean    [3d, visualis, anim, play, role, mani, areas,,...
descr_stem     [3d, visualis, and, anim, play, a, role, in, m...
Name: 0, dtype: object

For example, the words "play" and "in" are removed.

#### Removing Punctuation with NLTK

To further prepare the description for the search engine, the next step involves eliminating punctuation.

In [25]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\rochd\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [48]:
#we take care here of special caracters such as '!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~'
import string

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

So, again we take a look at the description of the 1st row:

In [49]:
dataset.loc[0, 'description']

"3D visualisation and animation play a role in many areas, and the popularity of these media just keeps growing. Digital animation provides the eye-catching special effects in the 21st century's favourite films and television shows; 3D design is also essential to everyday work in everything from computer games development, online virtual world development and industrial design to marketing, product design and architecture. GCU's programme in 3D Design for Virtual Environments will help you develop the skills to thrive in a successful career as a visual designer. The programme is practical and career-focused, oriented towards current industry needs, technology and practice. No prior knowledge of 3D design is required."

The NLTK's word_tokenizer provides a robust method for breaking down words within a string, returning the results as a list. Instead of relying on the split() method and NLTK's punctuation package, we can leverage the word_tokenizer to separate words. Afterward, we can employ the isalnum() method to eliminate punctuation, checking if a word contains alphanumeric characters or not.

In [28]:
words = nltk.word_tokenize(dataset.loc[0, 'description'])
words

['3D',
 'visualisation',
 'and',
 'animation',
 'play',
 'a',
 'role',
 'in',
 'many',
 'areas',
 ',',
 'and',
 'the',
 'popularity',
 'of',
 'these',
 'media',
 'just',
 'keeps',
 'growing',
 '.',
 'Digital',
 'animation',
 'provides',
 'the',
 'eye-catching',
 'special',
 'effects',
 'in',
 'the',
 '21st',
 'century',
 "'s",
 'favourite',
 'films',
 'and',
 'television',
 'shows',
 ';',
 '3D',
 'design',
 'is',
 'also',
 'essential',
 'to',
 'everyday',
 'work',
 'in',
 'everything',
 'from',
 'computer',
 'games',
 'development',
 ',',
 'online',
 'virtual',
 'world',
 'development',
 'and',
 'industrial',
 'design',
 'to',
 'marketing',
 ',',
 'product',
 'design',
 'and',
 'architecture',
 '.',
 'GCU',
 "'s",
 'programme',
 'in',
 '3D',
 'Design',
 'for',
 'Virtual',
 'Environments',
 'will',
 'help',
 'you',
 'develop',
 'the',
 'skills',
 'to',
 'thrive',
 'in',
 'a',
 'successful',
 'career',
 'as',
 'a',
 'visual',
 'designer',
 '.',
 'The',
 'programme',
 'is',
 'practical',


We can verify if each word in the obtained list is alphanumeric or not.

In [29]:
for word_i in words:
    print(f"WORD: {word_i}\tisAlNum: {word_i.isalnum()}")


WORD: 3D	isAlNum: True
WORD: visualisation	isAlNum: True
WORD: and	isAlNum: True
WORD: animation	isAlNum: True
WORD: play	isAlNum: True
WORD: a	isAlNum: True
WORD: role	isAlNum: True
WORD: in	isAlNum: True
WORD: many	isAlNum: True
WORD: areas	isAlNum: True
WORD: ,	isAlNum: False
WORD: and	isAlNum: True
WORD: the	isAlNum: True
WORD: popularity	isAlNum: True
WORD: of	isAlNum: True
WORD: these	isAlNum: True
WORD: media	isAlNum: True
WORD: just	isAlNum: True
WORD: keeps	isAlNum: True
WORD: growing	isAlNum: True
WORD: .	isAlNum: False
WORD: Digital	isAlNum: True
WORD: animation	isAlNum: True
WORD: provides	isAlNum: True
WORD: the	isAlNum: True
WORD: eye-catching	isAlNum: False
WORD: special	isAlNum: True
WORD: effects	isAlNum: True
WORD: in	isAlNum: True
WORD: the	isAlNum: True
WORD: 21st	isAlNum: True
WORD: century	isAlNum: True
WORD: 's	isAlNum: False
WORD: favourite	isAlNum: True
WORD: films	isAlNum: True
WORD: and	isAlNum: True
WORD: television	isAlNum: True
WORD: shows	isAlNum: True
WO

Here is a list of all alphanumeric words in the given list. You can observe that punctuation has been excluded.

In [30]:
[word_i for word_i in words if word_i.isalnum()]

['3D',
 'visualisation',
 'and',
 'animation',
 'play',
 'a',
 'role',
 'in',
 'many',
 'areas',
 'and',
 'the',
 'popularity',
 'of',
 'these',
 'media',
 'just',
 'keeps',
 'growing',
 'Digital',
 'animation',
 'provides',
 'the',
 'special',
 'effects',
 'in',
 'the',
 '21st',
 'century',
 'favourite',
 'films',
 'and',
 'television',
 'shows',
 '3D',
 'design',
 'is',
 'also',
 'essential',
 'to',
 'everyday',
 'work',
 'in',
 'everything',
 'from',
 'computer',
 'games',
 'development',
 'online',
 'virtual',
 'world',
 'development',
 'and',
 'industrial',
 'design',
 'to',
 'marketing',
 'product',
 'design',
 'and',
 'architecture',
 'GCU',
 'programme',
 'in',
 '3D',
 'Design',
 'for',
 'Virtual',
 'Environments',
 'will',
 'help',
 'you',
 'develop',
 'the',
 'skills',
 'to',
 'thrive',
 'in',
 'a',
 'successful',
 'career',
 'as',
 'a',
 'visual',
 'designer',
 'The',
 'programme',
 'is',
 'practical',
 'and',
 'oriented',
 'towards',
 'current',
 'industry',
 'needs',
 'tec

Now, let's revisit the 'descr_clean' column. We aim to include only stemmed words that are not stopwords.

In [31]:
dataset['descr_clean'] = dataset.description.apply(lambda row: [porterstemmer.stem(word) for word in nltk.word_tokenize(row) if not word in lst_stopwords and word.isalnum()])
dataset['descr_clean'].head

<bound method NDFrame.head of 0       [3d, visualis, anim, play, role, mani, area, p...
1       [busi, govern, reli, sound, financi, knowledg,...
2       [the, analyt, toxicolog, msc, uniqu, studi, co...
3       [thi, programm, design, equip, student, specia...
4       [enhanc, practic, global, top, 100, univers, g...
                              ...                        
5995    [allergi, increas, global, health, problem, th...
5996    [thi, new, postgradu, certif, allergi, clinic,...
5997    [we, world, allergi, organis, centr, excel, de...
5998    [a, research, degre, open, door, work, researc...
5999    [thi, programm, allow, explor, american, histo...
Name: descr_clean, Length: 5982, dtype: object>

In [32]:
dataset.loc[0, 'descr_clean']

['3d',
 'visualis',
 'anim',
 'play',
 'role',
 'mani',
 'area',
 'popular',
 'media',
 'keep',
 'grow',
 'digit',
 'anim',
 'provid',
 'special',
 'effect',
 '21st',
 'centuri',
 'favourit',
 'film',
 'televis',
 'show',
 '3d',
 'design',
 'also',
 'essenti',
 'everyday',
 'work',
 'everyth',
 'comput',
 'game',
 'develop',
 'onlin',
 'virtual',
 'world',
 'develop',
 'industri',
 'design',
 'market',
 'product',
 'design',
 'architectur',
 'gcu',
 'programm',
 '3d',
 'design',
 'virtual',
 'environ',
 'help',
 'develop',
 'skill',
 'thrive',
 'success',
 'career',
 'visual',
 'design',
 'the',
 'programm',
 'practic',
 'orient',
 'toward',
 'current',
 'industri',
 'need',
 'technolog',
 'practic',
 'no',
 'prior',
 'knowledg',
 '3d',
 'design',
 'requir']

#### SpaCy

We'll highlight the capabilities of SpaCy, a powerful and modern package, although we won't extensively use it in this context.

In [33]:
import spacy

In [34]:
import spacy.cli
spacy.cli.download("en_core_web_sm")


✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [50]:
nlp = spacy.load("en_core_web_sm")
doc = nlp(dataset.loc[0, 'description'])
doc

3D visualisation and animation play a role in many areas, and the popularity of these media just keeps growing. Digital animation provides the eye-catching special effects in the 21st century's favourite films and television shows; 3D design is also essential to everyday work in everything from computer games development, online virtual world development and industrial design to marketing, product design and architecture. GCU's programme in 3D Design for Virtual Environments will help you develop the skills to thrive in a successful career as a visual designer. The programme is practical and career-focused, oriented towards current industry needs, technology and practice. No prior knowledge of 3D design is required.

We can loop through each entity in our "doc" variable and examine its characteristics, including:

- `.text`: The word itself.
- `.label_`: A label assigned by SpaCy for categorization.
- `.start_char`: The position of the first character of the word.
- `.end_char`: The position of the last character of the word.


In [52]:
for ent_i in doc.ents:
    print(f"TEXT: {ent_i.text}, LABEL_: {ent_i.label_}, START_CHAR: {ent_i.start_char}, END_CHAR: {ent_i.end_char}")

TEXT: Digital, LABEL_: ORG, START_CHAR: 112, END_CHAR: 119
TEXT: the 21st century's, LABEL_: DATE, START_CHAR: 175, END_CHAR: 193
TEXT: GCU, LABEL_: ORG, START_CHAR: 426, END_CHAR: 429
TEXT: 3D Design for Virtual Environments, LABEL_: ORG, START_CHAR: 445, END_CHAR: 479


We can also examine additional functionalities associated with each token:

In [39]:
for token in doc:
    print(token, token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
            token.shape_, token.is_alpha, token.is_stop)

3D 3D 3d ADJ JJ amod dX False False
visualisation visualisation visualisation NOUN NN nsubj xxxx True False
and and and CCONJ CC cc xxx True True
animation animation animation NOUN NN conj xxxx True False
play play play VERB VBP ROOT xxxx True False
a a a DET DT det x True True
role role role NOUN NN dobj xxxx True False
in in in ADP IN prep xx True True
many many many ADJ JJ amod xxxx True True
areas areas area NOUN NNS pobj xxxx True False
, , , PUNCT , punct , False False
and and and CCONJ CC cc xxx True True
the the the DET DT det xxx True True
popularity popularity popularity NOUN NN nsubj xxxx True False
of of of ADP IN prep xx True True
these these these DET DT det xxxx True True
media media medium NOUN NNS pobj xxxx True False
just just just ADV RB advmod xxxx True True
keeps keeps keep VERB VBZ conj xxxx True False
growing growing grow VERB VBG xcomp xxxx True False
. . . PUNCT . punct . False False
Digital Digital digital ADJ JJ amod Xxxxx True False
animation animation anima

As stated before, SpaCy will not be utilized in our search engine.

### 2.0.1 Preprocessing the fees column

Additionally, we aim to convert the "fees" field into a numeric format. Currently, the dataset contains textual information for this attribute. To address this, propose an appropriate method, such as utilizing regular expressions to identify currency symbols, to extract information. In cases where multiple fee values are present, prioritize retrieving only the highest fee.

After obtaining numeric information, you may encounter various currencies. To streamline this process, seek guidance from ChatGPT on selecting and implementing an API for currency conversion. This conversion aims to standardize the "fees" column to a common currency of your preference, be it USD, EUR, or any other choice. Ultimately, you will have a float column named "fees" in the chosen common currency.

In [40]:
for fee_i in (dataset.fees[:10]):
    print(fee_i)

Please see the university website for further information on fees for this course.
UK: £18,000 (Total) International: £34,750 (Total)
Please see the university website for further information on fees for this course.
Please see the university website for further information on fees for this course.
Please see the university website for further information on fees for this course.
Part time - £7,050
Please see the university website for further information on fees for this course.
Please see the university website for further information on fees for this course.
Please see the university website for further information on fees for this course.
Our tuition fee for UK students starting full-time study in 2024/25 is £10,310 for the course.  Please see the university website for further information on fees for this course.


Here we're looking at fees column on the 1st row:

In [41]:
dataset.fees.iloc[0]

'Please see the university website for further information on fees for this course.'

Sometimes, there are instances where no figure is mentioned, while in other cases, multiple figures may be referenced. Therefore, it's important to handle these variations.

I had some issues to get exhanges rates.

### 2.1. Conjunctive query

In the initial iteration of the search engine, our focus was limited to the course descriptions. This implies that queries will be assessed exclusively based on the information available in the course descriptions.

#### 2.1.1 Create your index!

Before constructing the index, follow these steps:

1. Generate a file named "vocabulary" in your preferred format, establishing a mapping of each word to an integer (term_id).
2. The initial task in your homework is to establish the Inverted Index. This index takes the form of a dictionary structured as follows:


{
    term_id_1: [document_1, document_2, document_4],
    term_id_2: [document_1, document_3, document_5, document_6],
}


Here, 'document_i' represents the identifier of a document that contains the specific word corresponding to the term_id.

Tip: To avoid recomputing the inverted index every time you use the Search Engine, consider storing it in a separate file and loading it into memory as needed.

Let's look another time at the "descr_clean" column:

In [54]:
dataset.descr_clean

0       [3d, visualis, anim, play, role, mani, area, p...
1       [busi, govern, reli, sound, financi, knowledg,...
2       [the, analyt, toxicolog, msc, uniqu, studi, co...
3       [thi, programm, design, equip, student, specia...
4       [enhanc, practic, global, top, 100, univers, g...
                              ...                        
5995    [allergi, increas, global, health, problem, th...
5996    [thi, new, postgradu, certif, allergi, clinic,...
5997    [we, world, allergi, organis, centr, excel, de...
5998    [a, research, degre, open, door, work, researc...
5999    [thi, programm, allow, explor, american, histo...
Name: descr_clean, Length: 5982, dtype: object

To build the vocabulary, we have the option to employ either of the following two approaches:

##### Approach 1: Using Python Sets

Let's initialize the vocabulary as an empty set.

In [55]:
vocabulary = set()

We can consider including each word from every row in the set.

In [56]:
dataset.descr_clean.apply(lambda row: [vocabulary.add(word) for word in row])

0       [None, None, None, None, None, None, None, Non...
1       [None, None, None, None, None, None, None, Non...
2       [None, None, None, None, None, None, None, Non...
3       [None, None, None, None, None, None, None, Non...
4       [None, None, None, None, None, None, None, Non...
                              ...                        
5995    [None, None, None, None, None, None, None, Non...
5996    [None, None, None, None, None, None, None, Non...
5997    [None, None, None, None, None, None, None, Non...
5998    [None, None, None, None, None, None, None, Non...
5999    [None, None, None, None, None, None, None, Non...
Name: descr_clean, Length: 5982, dtype: object

Each repeated word will appear only once within the set.

In [57]:
vocabulary

{'nokia',
 'perceiv',
 'formal',
 'buzz',
 'squar',
 'dysfunct',
 'pound',
 'eagerli',
 'refresh',
 'studley',
 'virolog',
 'sp9',
 'thermofluid',
 'tissu',
 'ansac',
 'accuraci',
 'internet',
 '8910',
 'where',
 'mental',
 'overload',
 'estat',
 'ihnen',
 'theoris',
 'outsid',
 'hu',
 '6',
 'cinema',
 '17th',
 'util',
 'microelectron',
 'sharpen',
 'thorough',
 'increasingli',
 '1971',
 'clariti',
 'rijeka',
 'altruism',
 'phytopharmacolog',
 'twin',
 'region',
 'arous',
 'inventori',
 'spread',
 'enzym',
 'telecommun',
 'nanostructur',
 'postdoctor',
 'sussex',
 'postharvest',
 'scenario',
 'greatest',
 'inject',
 'breakthrough',
 '13th',
 'success',
 'golden',
 'winner',
 'achiev',
 'reservoir',
 'impun',
 'bedsid',
 'weg',
 'guest',
 'secclo',
 'curriculum',
 'steem',
 'unintend',
 'utrecht',
 'cyberpsycholog',
 'jewelri',
 'nova',
 'compliment',
 'offend',
 'effort',
 'vr',
 'selv',
 'polic',
 'dollar',
 'cyberthreat',
 'scroll',
 'hit',
 'xjtlu',
 'leben',
 'supervis',
 'hewm',
 

##### Approach 2: Using Python Collections

Another approach is to use the counter and reduce packages:

In [58]:
from collections import Counter
from functools import reduce

In [59]:
vocabulary_alt = Counter(reduce(lambda x, y: x + y, dataset.descr_clean.values)).keys()

In [60]:
vocabulary_alt

dict_keys(['3d', 'visualis', 'anim', 'play', 'role', 'mani', 'area', 'popular', 'media', 'keep', 'grow', 'digit', 'provid', 'special', 'effect', '21st', 'centuri', 'favourit', 'film', 'televis', 'show', 'design', 'also', 'essenti', 'everyday', 'work', 'everyth', 'comput', 'game', 'develop', 'onlin', 'virtual', 'world', 'industri', 'market', 'product', 'architectur', 'gcu', 'programm', 'environ', 'help', 'skill', 'thrive', 'success', 'career', 'visual', 'the', 'practic', 'orient', 'toward', 'current', 'need', 'technolog', 'no', 'prior', 'knowledg', 'requir', 'busi', 'govern', 'reli', 'sound', 'financi', 'underpin', 'strategi', 'thi', 'cours', 'profession', 'advanc', 'modern', 'theori', 'account', 'control', 'well', 'understand', 'organis', 'context', 'you', 'cover', 'fundament', 'topic', 'corpor', 'financ', 'report', 'option', 'modul', 'allow', 'specialis', 'rang', 'intern', 'forens', 'abl', 'appli', 'learn', 'case', 'studi', 'simul', 'test', 'genuin', 'scenario', 'analyt', 'toxicolog',

##### Assign Unique ID to each item in the Vocab

To create the inverted matrix, we must assign integer values to each term in the vocabulary. This task can be accomplished through two methods:

###### Approach 1: Using For-Loop

In [61]:
index = {}
unique_id = 1
for word in list(vocabulary_alt):
  index[unique_id] = word
  unique_id+=1

In [62]:
index

{1: '3d',
 2: 'visualis',
 3: 'anim',
 4: 'play',
 5: 'role',
 6: 'mani',
 7: 'area',
 8: 'popular',
 9: 'media',
 10: 'keep',
 11: 'grow',
 12: 'digit',
 13: 'provid',
 14: 'special',
 15: 'effect',
 16: '21st',
 17: 'centuri',
 18: 'favourit',
 19: 'film',
 20: 'televis',
 21: 'show',
 22: 'design',
 23: 'also',
 24: 'essenti',
 25: 'everyday',
 26: 'work',
 27: 'everyth',
 28: 'comput',
 29: 'game',
 30: 'develop',
 31: 'onlin',
 32: 'virtual',
 33: 'world',
 34: 'industri',
 35: 'market',
 36: 'product',
 37: 'architectur',
 38: 'gcu',
 39: 'programm',
 40: 'environ',
 41: 'help',
 42: 'skill',
 43: 'thrive',
 44: 'success',
 45: 'career',
 46: 'visual',
 47: 'the',
 48: 'practic',
 49: 'orient',
 50: 'toward',
 51: 'current',
 52: 'need',
 53: 'technolog',
 54: 'no',
 55: 'prior',
 56: 'knowledg',
 57: 'requir',
 58: 'busi',
 59: 'govern',
 60: 'reli',
 61: 'sound',
 62: 'financi',
 63: 'underpin',
 64: 'strategi',
 65: 'thi',
 66: 'cours',
 67: 'profession',
 68: 'advanc',
 69: '

###### Approach 2: Using Pandas DataFrames

We instantiate a Pandas DataFrame named "terms" with a column labeled "term" to store the vocabulary terms.

In [63]:
terms = pd.DataFrame(data=list(vocabulary_alt), columns=['term'])

In [64]:
terms

term
0               3d
1         visualis
2             anim
3             play
4             role
...            ...
6902      recherch
6903   mathématiqu
6904        allerg
6905       slaveri
6906  dictatorship

[6907 rows x 1 columns]

##### Creating the Inverted Index

Question: Which documents among the range of 0 to 5999 contain the term "3D," considering that the term "3D" is located at terms.loc[0, "term"]?

In [65]:
dataset.descr_clean.apply(lambda row: terms.loc[0, "term"] in row)

0        True
1       False
2       False
3       False
4       False
        ...  
5995    False
5996    False
5997    False
5998    False
5999    False
Name: descr_clean, Length: 5982, dtype: bool

Using a mask to identify documents that specifically contain the term "3D."

In [66]:
dataset.index[dataset.descr_clean.apply(lambda row: terms.loc[0, "term"] in row)]

Index([   0,  923, 1592, 2033, 2036, 2037, 3239, 3339, 3691, 4401, 4467, 5309,
       5346, 5357, 5868],
      dtype='int64')

Once again, we employ the identical mask, but this time, to display both `courseName` and `description`.

In [67]:
dataset[["courseName", "description"]][dataset.descr_clean.apply(lambda row: terms.loc[0, "term"] in row)]

courseName  \
0              3D Design for Virtual Environments - MSc   
923                    Chemistry - MPhil/MSc (Research)   
1592                        Creative Technologies (MSc)   
2033                           Digital Anthropology MSc   
2036                    Digital Audio Engineering - MSc   
2037                    Digital Audio Engineering - MSc   
3239                             Game Engineering - MSc   
3339    Geospatial Sciences (Building Information Mo...   
3691                                      Physics - MSc   
4401                     3D Computer Games Design - MSc   
4467    Landscape Archaeology and Digital Heritage -...   
5309               Master of Science in Computer Vision   
5346                       Additive Manufacturing - MSc   
5357         Additive Manufacturing and 3D Printing MSc   
5868    Advanced Product Design Engineering & Manufa...   

                                            description  
0     3D visualisation and animation play a role in ...  
923   Our research groups are involved in projects a...  
1592  Combine your passion for creative art and desi...  
2033  The MSc in Digital Anthropology, the first and...  
2036  On our MSc in Digital Audio Engineering, you w...  
2037  On our MSc in Digital Audio Engineering, you w...  
3239  UCA's new MSc Game Engineering course aims to ...  
3339  The Geospatial Sciences (Building Information ...  
3691  This course is for you if you’re interested in...  
4401  Get a flying start in the games industry. If y...  
4467  3D methods of digitally documenting objects, s...  
5309  Introduction This scientific field studies how...  
5346  Additive Manufacturing, or 3D printing, is an ...  
5357  Whether it is creating advanced engineering co...  
5868  This course examines the latest developments i...

We employ "tqdm.notebook" solely for its "progress_apply" method usage later on.

In [68]:
from tqdm.notebook import tqdm

tqdm.pandas()

Now, our objective is to introduce a new column, named 'reverse,' to the 'terms' dataframe. This column will hold a list of all the rows that contain the corresponding term or word.

In [70]:

terms['reverse'] = terms.term.progress_apply(lambda item: list(dataset.loc[dataset.descr_clean.apply(lambda row: item in row)].index))

  0%|          | 0/6907 [00:00<?, ?it/s]

Let's take a look at the top 10:

In [71]:
terms.loc[0:9]

term                                            reverse
0        3d  [0, 923, 1592, 2033, 2036, 2037, 3239, 3339, 3...
1  visualis  [0, 78, 306, 470, 471, 474, 738, 754, 796, 797...
2      anim  [0, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34...
3      play  [0, 34, 42, 43, 66, 103, 249, 250, 254, 357, 3...
4      role  [0, 5, 31, 33, 34, 43, 46, 58, 103, 107, 119, ...
5      mani  [0, 33, 36, 49, 79, 94, 95, 99, 102, 109, 111,...
6      area  [0, 4, 11, 13, 18, 36, 47, 51, 53, 71, 75, 90,...
7   popular  [0, 62, 322, 532, 1047, 1164, 1165, 1166, 1519...
8     media  [0, 54, 196, 284, 363, 364, 447, 476, 546, 741...
9      keep  [0, 119, 396, 462, 530, 619, 686, 687, 1332, 1...

To enhance convenience, let's store our inverted index in a CSV file.

In [72]:
terms.to_csv('inverted_index.csv', index=False)

#### Executing the Query

At last, we can create a straightforward search engine function named 'execute_query':

In [73]:
def execute_query(query, inverted_index, dataset):
    # Split the query into terms and stem each term
    query_terms = [porterstemmer.stem(word) for word in query.lower().split()]

    # Retrieve the list of document indices for each query term
    list_of_documents = [set(inverted_index[inverted_index['term'] == term_i]['reverse'].values[0])
                         for term_i in query_terms if term_i in inverted_index['term'].values]

    # Intersect the document lists to find documents that contain all query terms
    if list_of_documents:
        docs_containing_all_terms = set.intersection(*list_of_documents)
        # Convert set to list before using it as an indexer
        docs_containing_all_terms = list(docs_containing_all_terms)
    else:
        docs_containing_all_terms = []

    results = dataset.loc[docs_containing_all_terms, ['courseName', 'universityName', 'description', 'url']]

    return results.reset_index(drop=True)


There is a way we could use the search engine:

In [74]:
# Example usage:
sample_query = "advanced knowledge"
query_results = execute_query(sample_query, terms, dataset)
(query_results)

courseName                 universityName  \
0            Accounting and Finance - MSc            University of Leeds   
1               Analytical Toxicology MSc          King’s College London   
2         Digital Design and Branding MSc       Brunel University London   
3      Digital Design and Manufacture MSc        University of Edinburgh   
4                     Stroke Medicine MSc           Learna | Diploma MSc   
..                                    ...                            ...   
444          International Business - MSc          University of Glasgow   
445               Diabetes Practice - MSc             Cardiff University   
446    Diabetes Practice MSc/PGDip/PGCert             Swansea University   
447              Diagnostic Imaging - MSc  Glasgow Caledonian University   
448            Diagnostic Radiography MSc        University College Cork   

                                           description  \
0    Businesses and governments rely on sound finan...   
1    The Analytical Toxicology MSc is a unique stud...   
2    Our Digital Design and Branding MSc degree is ...   
3    With the transition to industry 4.0, digital d...   
4    Postgraduate training in stroke care is limite...   
..                                                 ...   
444  International Business will provide you with a...   
445  The MSc Diabetes Practice aims to equip health...   
446  If you are a health professional with a specia...   
447  Designed to train a new generation of leaders ...   
448  Our MSc Diagnostic Radiography programme is an...   

                                                   url  
0    https://www.findamasters.com/masters-degrees/c...  
1    https://www.findamasters.com/masters-degrees/c...  
2    https://www.findamasters.com/masters-degrees/c...  
3    https://www.findamasters.com/masters-degrees/c...  
4    https://www.findamasters.com/masters-degrees/c...  
..                                                 ...  
444  https://www.findamasters.com/masters-degrees/c...  
445  https://www.findamasters.com/masters-degrees/c...  
446  https://www.findamasters.com/masters-degrees/c...  
447  https://www.findamasters.com/masters-degrees/c...  
448  https://www.findamasters.com/masters-degrees/c...  

[449 rows x 4 columns]

In [112]:
# another example
sample_query = "financial management"
query_results = execute_query(sample_query, terms, dataset)
(query_results)

courseName  \
0           Master in Global Management at ESMT Berlin   
1                         Accounting and Finance - MSc   
2                MSc Finance and Investment Management   
3                     Master in Health Care Management   
4                             FinTech Management - MSc   
..                                                 ...   
231                       Engineering Management (MSc)   
232    Master in Global Logistics and Supply Chain ...   
233                                  Master of Finance   
234                Construction Project Management MSc   
235            MSc Project Management for Construction   

                        universityName  \
0                          ESMT Berlin   
1                    Bangor University   
2              University of Liverpool   
3                   Harvard University   
4                    Ulster University   
..                                 ...   
231      University of Gloucestershire   
232  Kuehne Logistics University - KLU   
233           York University (Canada)   
234           University of Portsmouth   
235           University of Portsmouth   

                                           description  \
0    The ESMT Berlin Master in Global Management pr...   
1    This degree programme provides the opportunity...   
2    A career in finance and investment management ...   
3    Today, leading a health care organization take...   
4    Gain a solid grounding in key aspects of finan...   
..                                                 ...   
231  The modules you will study include Leading Eng...   
232  Our MSc in Global Logistics and Supply Chain M...   
233  The “must-have” degree for specialized financi...   
234  Establish yourself in the global construction ...   
235  Start date: January 2024 A level of management...   

                                                   url  
0    https://www.findamasters.com/masters-degrees/c...  
1    https://www.findamasters.com/masters-degrees/c...  
2    https://www.findamasters.com/masters-degrees/c...  
3    https://www.findamasters.com/masters-degrees/c...  
4    https://www.findamasters.com/masters-degrees/c...  
..                                                 ...  
231  https://www.findamasters.com/masters-degrees/c...  
232  https://www.findamasters.com/masters-degrees/c...  
233  https://www.findamasters.com/masters-degrees/c...  
234  https://www.findamasters.com/masters-degrees/c...  
235  https://www.findamasters.com/masters-degrees/c...  

[236 rows x 4 columns]

### 2.2 Conjunctive query & Ranking score

#### TF-IDF

Now, an alternative approach for defining our search engine involves utilizing the TF-IDF score :

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [77]:
tfidf = TfidfVectorizer(input='content', lowercase=False, tokenizer=lambda text: text) # , max_df=0.1

In [78]:
results = tfidf.fit_transform(dataset.descr_clean)

C:\Users\rochd\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [79]:
results

<5982x6907 sparse matrix of type '<class 'numpy.float64'>'
	with 232331 stored elements in Compressed Sparse Row format>

In [80]:
result_dense = results.todense()

In [81]:

result_dense

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

Ultimately, a Pandas DataFrame can be created utilizing the scores present in the 'descr_clean' column.

In [82]:
tfidf_data = pd.DataFrame(result_dense.tolist(), index=dataset.index, columns=tfidf.get_feature_names_out())

In [83]:
len(tfidf_data)

5982

In [84]:
tfidf_data

1   10       100  1000  104k   11  11th   12  120  125k  ...  zoonosi  \
0     0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
1     0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
2     0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
3     0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
4     0.0  0.0  0.141114   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
...   ...  ...       ...   ...   ...  ...   ...  ...  ...   ...  ...      ...   
5995  0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
5996  0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
5997  0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
5998  0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   
5999  0.0  0.0  0.000000   0.0   0.0  0.0   0.0  0.0  0.0   0.0  ...      0.0   

      zoonot   zu  zudem  zum  zur  zurich  zwingen  école  ísafjörður  
0        0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
1        0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
2        0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
3        0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
4        0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
...      ...  ...    ...  ...  ...     ...      ...    ...         ...  
5995     0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
5996     0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
5997     0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
5998     0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  
5999     0.0  0.0    0.0  0.0  0.0     0.0      0.0    0.0         0.0  

[5982 rows x 6907 columns]

To gain an understanding of the DataFrame's structure, let's examine a subset of its central columns.

In [85]:
tfidf_data.iloc[:, 1150:1165]

ced  cedex  cee  cef  ceid  celci  celebr  cell  cellebrit  cellular  \
0     0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
1     0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
2     0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
3     0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
4     0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
...   ...    ...  ...  ...   ...    ...     ...   ...        ...       ...   
5995  0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
5996  0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
5997  0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
5998  0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   
5999  0.0    0.0  0.0  0.0   0.0    0.0     0.0   0.0        0.0       0.0   

      celtic  cem  cement  cen  ceng  
0        0.0  0.0     0.0  0.0   0.0  
1        0.0  0.0     0.0  0.0   0.0  
2        0.0  0.0     0.0  0.0   0.0  
3        0.0  0.0     0.0  0.0   0.0  
4        0.0  0.0     0.0  0.0   0.0  
...      ...  ...     ...  ...   ...  
5995     0.0  0.0     0.0  0.0   0.0  
5996     0.0  0.0     0.0  0.0   0.0  
5997     0.0  0.0     0.0  0.0   0.0  
5998     0.0  0.0     0.0  0.0   0.0  
5999     0.0  0.0     0.0  0.0   0.0  

[5982 rows x 15 columns]

In [86]:
tfidf_data.loc[terms.term == "3d"]["3d"]

0    0.558084
Name: 3d, dtype: float64

At index 0, the term '3D' is prominently featured. Let's explore the frequency of its usage :

In [87]:
Counter(dataset.loc[0, 'descr_clean'])['3d']

4

We have observed the utilization of the word 'govern' in index 1, occurring once. Now, let's delve into this occurrence :

In [88]:
Counter(dataset.loc[1, 'descr_clean'])['govern']

1

When examining the term "finance" in the `tfidf_data`, it becomes evident that it possesses a TFIDF score of 0.0 in the majority of the documents.

In [89]:
# Obviously we cannot mention "finance" exactly as is, but we have to stemm it first into "financ"
tfidf_data.financ

0       0.000000
1       0.213729
2       0.000000
3       0.145655
4       0.000000
          ...   
5995    0.000000
5996    0.000000
5997    0.000000
5998    0.000000
5999    0.000000
Name: financ, Length: 5982, dtype: float64

Let's examine all the documents where the term 'finance' is mentioned :

In [90]:
tfidf_data.loc[tfidf_data.financ > 0, ['financ']]

financ
1     0.213729
3     0.145655
91    0.080973
93    0.105921
100   0.112638
...        ...
5845  0.227227
5894  0.117534
5932  0.113638
5960  0.081390
5985  0.127563

[464 rows x 1 columns]

In [91]:
dataset[tfidf_data.financ > 0][["courseName", "description"]]

courseName  \
1                          Accounting and Finance - MSc   
3                   Entrepreneurship & Innovation - MSc   
91      Environmental, Social, Governance (ESG) Mana...   
93                           Applied Data Science - MSc   
100     Applied data science for banking and finance...   
...                                                 ...   
5845                        Economics and Finance - MSc   
5894    Advanced Technology for Financial Computing ...   
5932                        Aerospace Engineering (MSc)   
5960                             Agricultural Economics   
5985          Air Transport Planning and Management MSc   

                                            description  
1     Businesses and governments rely on sound finan...  
3     This programme is designed to equip students w...  
91    More than ever ESG is essential for businesses...  
93    Our Applied Data Science Masters programme is ...  
100   The Master’s degree of Applied Data Science fo...  
...                                                 ...  
5845  This course provides an opportunity to combine...  
5894  This programme will provide you with a critica...  
5932  This course provides a strategic and practical...  
5960  Food crises, commodity price booms and busts, ...  
5985  This course has been developed to meet the nee...  

[464 rows x 2 columns]

It's evident that the term "you" appears frequently across many documents, yet it has a relatively low TF-IDF score.

In [92]:
tfidf_data.loc[tfidf_data["you"] > 0]["you"]

1       0.143833
6       0.050562
8       0.108902
15      0.076762
16      0.075500
          ...   
5989    0.076589
5990    0.067682
5991    0.066887
5997    0.057537
5999    0.041176
Name: you, Length: 1486, dtype: float64

We can add a new column called 'descr_len' to our dataset, which represents the number of terms or words in each description cell. This column will be appended at the end of our dataset.

In [93]:
dataset['descr_len'] = dataset.descr_clean.apply(lambda row: len(row))

In [94]:
dataset.loc[[1, 2, 9, 12, 14], 'descr_len']

1     59
2     27
9     15
12     5
14    65
Name: descr_len, dtype: int64

### Cosine Similarity

Cosine Similarity emerges as a robust metric for constructing our secondary search engine.

In [95]:
from sklearn.metrics.pairwise import cosine_similarity

We generate a DataFrame illustrating the Cosine Similarity between each pair of our 6000 documents.

In [96]:
cossim_data = pd.DataFrame(cosine_similarity(tfidf_data), index=dataset.index, columns=dataset.index)

In [97]:
cossim_data

0         1         2         3         4         5         6     \
0     1.000000  0.044896  0.017311  0.062301  0.028271  0.034360  0.070342   
1     0.044896  1.000000  0.098026  0.096449  0.021572  0.028806  0.026257   
2     0.017311  0.098026  1.000000  0.020816  0.032284  0.042743  0.034030   
3     0.062301  0.096449  0.020816  1.000000  0.012793  0.016779  0.024242   
4     0.028271  0.021572  0.032284  0.012793  1.000000  0.062196  0.013736   
...        ...       ...       ...       ...       ...       ...       ...   
5995  0.030193  0.039091  0.035855  0.035377  0.070859  0.034376  0.014845   
5996  0.012265  0.021720  0.043225  0.043144  0.064227  0.068529  0.000000   
5997  0.034951  0.043321  0.023743  0.030867  0.130874  0.048449  0.016382   
5998  0.029310  0.060824  0.048526  0.055432  0.130633  0.122444  0.037089   
5999  0.005517  0.051947  0.015655  0.012699  0.017076  0.001610  0.006764   

          7         8         9     ...      5990      5991      5992  \
0     0.026444  0.024312  0.040890  ...  0.094114  0.066081  0.060399   
1     0.044869  0.043968  0.095974  ...  0.093382  0.043980  0.026459   
2     0.123045  0.009016  0.123079  ...  0.042001  0.042523  0.029054   
3     0.018312  0.018093  0.011931  ...  0.081671  0.036518  0.042325   
4     0.009294  0.024846  0.065112  ...  0.011187  0.031585  0.020140   
...        ...       ...       ...  ...       ...       ...       ...   
5995  0.030179  0.018701  0.064314  ...  0.016265  0.036910  0.030794   
5996  0.048048  0.009580  0.012659  ...  0.015783  0.067892  0.022590   
5997  0.034180  0.043561  0.000000  ...  0.025717  0.021576  0.020385   
5998  0.064269  0.043021  0.021296  ...  0.029986  0.054539  0.004431   
5999  0.055193  0.013550  0.004577  ...  0.015477  0.051912  0.003271   

          5993      5994      5995      5996      5997      5998      5999  
0     0.015575  0.000000  0.030193  0.012265  0.034951  0.029310  0.005517  
1     0.022829  0.007139  0.039091  0.021720  0.043321  0.060824  0.051947  
2     0.026443  0.020243  0.035855  0.043225  0.023743  0.048526  0.015655  
3     0.019011  0.005042  0.035377  0.043144  0.030867  0.055432  0.012699  
4     0.004987  0.006360  0.070859  0.064227  0.130874  0.130633  0.017076  
...        ...       ...       ...       ...       ...       ...       ...  
5995  0.004916  0.011777  1.000000  0.319122  0.506296  0.056496  0.007913  
5996  0.005718  0.011568  0.319122  1.000000  0.290336  0.085569  0.010977  
5997  0.014168  0.014551  0.506296  0.290336  1.000000  0.126371  0.002369  
5998  0.020900  0.038562  0.056496  0.085569  0.126371  1.000000  0.058893  
5999  0.006021  0.005185  0.007913  0.010977  0.002369  0.058893  1.000000  

[5982 rows x 5982 columns]

For instance, we can examine all the rows where the TF-IDF score for the word "design" is non-zero.

In [98]:
tfidf_data.loc[tfidf_data.design > 0].index

Index([   0,    3,    6,    7,   15,   16,   17,   19,   24,   25,
       ...
       5982, 5984, 5985, 5986, 5987, 5989, 5990, 5991, 5992, 5995],
      dtype='int64', length=1561)

Afterward, we can examine the cosine similarity between those documents/rows and every other document.

In [99]:
cossim_data[tfidf_data.loc[tfidf_data.design > 0.1].index]

0         6         61        76        77        85        103   \
0     1.000000  0.070342  0.072319  0.093596  0.082283  0.131585  0.117771   
1     0.044896  0.026257  0.104755  0.065530  0.058123  0.082901  0.027663   
2     0.017311  0.034030  0.127910  0.049959  0.047881  0.027245  0.044165   
3     0.062301  0.024242  0.095927  0.086487  0.066019  0.039841  0.040293   
4     0.028271  0.013736  0.047589  0.018882  0.066568  0.092878  0.028719   
...        ...       ...       ...       ...       ...       ...       ...   
5995  0.030193  0.014845  0.053102  0.048664  0.041260  0.042642  0.051729   
5996  0.012265  0.000000  0.050280  0.058119  0.030327  0.047612  0.022931   
5997  0.034951  0.016382  0.033971  0.036117  0.047220  0.045777  0.025197   
5998  0.029310  0.037089  0.052779  0.081106  0.056889  0.071818  0.031393   
5999  0.005517  0.006764  0.017594  0.020140  0.017402  0.032128  0.018742   

          135       141       147   ...      5868      5884      5892  \
0     0.048727  0.072268  0.086113  ...  0.336127  0.081632  0.119661   
1     0.051501  0.061308  0.070455  ...  0.099293  0.064515  0.095014   
2     0.016520  0.044838  0.024865  ...  0.056523  0.085371  0.070849   
3     0.025827  0.014341  0.054653  ...  0.030551  0.028302  0.063867   
4     0.014086  0.050311  0.033591  ...  0.020747  0.005921  0.067758   
...        ...       ...       ...  ...       ...       ...       ...   
5995  0.016746  0.032387  0.031992  ...  0.033750  0.055963  0.033484   
5996  0.007829  0.016443  0.047491  ...  0.017635  0.013945  0.004876   
5997  0.008867  0.055943  0.039780  ...  0.014877  0.023145  0.051801   
5998  0.025629  0.016667  0.038880  ...  0.010654  0.024576  0.065209   
5999  0.012579  0.046626  0.059199  ...  0.006829  0.012191  0.024984   

          5905      5921      5944      5978      5984      5986      5992  
0     0.065641  0.064134  0.082214  0.085722  0.104644  0.091681  0.060399  
1     0.035909  0.101345  0.074909  0.135355  0.090061  0.055557  0.026459  
2     0.100817  0.012623  0.047672  0.044693  0.049227  0.031767  0.029054  
3     0.046748  0.110292  0.099437  0.073193  0.035708  0.055180  0.042325  
4     0.108476  0.011990  0.031380  0.036305  0.065920  0.030293  0.020140  
...        ...       ...       ...       ...       ...       ...       ...  
5995  0.047577  0.043714  0.029360  0.041091  0.055425  0.039944  0.030794  
5996  0.035962  0.018799  0.027717  0.030348  0.058108  0.014377  0.022590  
5997  0.202021  0.016268  0.026355  0.043296  0.021297  0.009255  0.020385  
5998  0.226728  0.016046  0.035675  0.032132  0.046088  0.038729  0.004431  
5999  0.011402  0.002327  0.006652  0.009459  0.022791  0.030315  0.003271  

[5982 rows x 389 columns]

In [100]:
dataset.loc[[0, 2, 1577]]

courseName  \
0              3D Design for Virtual Environments - MSc   
2                             Analytical Toxicology MSc   
1577    Counselling and Psychotherapy (Professional ...   

                     universityName  \
0     Glasgow Caledonian University   
2             King’s College London   
1577          University of Salford   

                                      facultyName  isItFullTime  \
0     School of Engineering and Built Environment          True   
2             Faculty of Life Sciences & Medicine          True   
1577                 School of Health and Society         False   

                                            description   startDate  \
0     3D visualisation and animation play a role in ...   September   
2     The Analytical Toxicology MSc is a unique stud...  See Course   
1577  During this course, you will undertake an in-d...   September   

                                                   fees    modality  \
0     Please see the university website for further ...         MSc   
2     Please see the university website for further ...         MSc   
1577  Please see the university website for further ...  PGDip, MSc   

                 duration        city         country administration  \
0        1 year full-time     Glasgow  United Kingdom      On Campus   
2     Full-time: One year      London  United Kingdom      On Campus   
1577  2-3 years Part-time  Manchester  United Kingdom      On Campus   

                                                    url  \
0     https://www.findamasters.com/masters-degrees/c...   
2     https://www.findamasters.com/masters-degrees/c...   
1577  https://www.findamasters.com/masters-degrees/c...   

                                             descr_stem  \
0     [3d, visualis, and, anim, play, a, role, in, m...   
2     [the, analyt, toxicolog, msc, is, a, uniqu, st...   
1577  [dure, thi, course,, you, will, undertak, an, ...   

                                            descr_clean  descr_len  
0     [3d, visualis, anim, play, role, mani, area, p...         72  
2     [the, analyt, toxicolog, msc, uniqu, studi, co...         27  
1577  [dure, cours, undertak, studi, approach, couns...         55

### 2nd Inverted Index

Now, let's generate the second inverted index DataFrame, referred to as 'terms2,' based on the homework description.

We initially duplicate our first [basic] index to the second one...

In [101]:
terms2 = terms[['term', 'reverse']].copy()

Next, we include an additional column called "tfidf_tuples". Consequently, we can observe each term in the "term" column, a compilation of all documents where that word has been referenced in the "reverse" column, and ultimately, a tuple representing the cosine similarity of each term across all documents/rows in the "tfidf_tuples" column.

In [102]:
terms2['tfidf_tuples'] = terms2.term.apply(lambda term: [(doc_id, tfidf_data.loc[doc_id, term])
                                                       for doc_id in tfidf_data.index if tfidf_data.loc[doc_id, term] > 0])

In [103]:
terms2

term                                            reverse  \
0               3d  [0, 923, 1592, 2033, 2036, 2037, 3239, 3339, 3...   
1         visualis  [0, 78, 306, 470, 471, 474, 738, 754, 796, 797...   
2             anim  [0, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34...   
3             play  [0, 34, 42, 43, 66, 103, 249, 250, 254, 357, 3...   
4             role  [0, 5, 31, 33, 34, 43, 46, 58, 103, 107, 119, ...   
...            ...                                                ...   
6902      recherch                                             [5994]   
6903   mathématiqu                                             [5994]   
6904        allerg                                             [5995]   
6905       slaveri                                             [5999]   
6906  dictatorship                                             [5999]   

                                           tfidf_tuples  
0     [(0, 0.5580842522585211), (923, 0.152852921404...  
1     [(0, 0.11960044691955087), (78, 0.119041928959...  
2     [(0, 0.2184275132043667), (23, 0.5054735077876...  
3     [(0, 0.09312374852562808), (34, 0.077513509080...  
4     [(0, 0.06817038680643188), (5, 0.1066488449838...  
...                                                 ...  
6902                         [(5994, 0.14173977060375)]  
6903                          [(5994, 0.2834795412075)]  
6904                      [(5995, 0.36854338677274523)]  
6905                       [(5999, 0.1549767656797962)]  
6906                       [(5999, 0.1549767656797962)]  

[6907 rows x 3 columns]

In the results displayed above, the word "3d" appears in rows 0 and 923. Observing the TF-IDF column reveals that the similarity between the word "3d" and document #0 is 0.5693. Additionally, the similarity between the word "3d" and document #923 is 0.1586. This pattern continues for other rows as well.

In [104]:
terms2["reverse"]

0       [0, 923, 1592, 2033, 2036, 2037, 3239, 3339, 3...
1       [0, 78, 306, 470, 471, 474, 738, 754, 796, 797...
2       [0, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34...
3       [0, 34, 42, 43, 66, 103, 249, 250, 254, 357, 3...
4       [0, 5, 31, 33, 34, 43, 46, 58, 103, 107, 119, ...
                              ...                        
6902                                               [5994]
6903                                               [5994]
6904                                               [5995]
6905                                               [5999]
6906                                               [5999]
Name: reverse, Length: 6907, dtype: object

In [105]:
terms2["tfidf_tuples"]

0       [(0, 0.5580842522585211), (923, 0.152852921404...
1       [(0, 0.11960044691955087), (78, 0.119041928959...
2       [(0, 0.2184275132043667), (23, 0.5054735077876...
3       [(0, 0.09312374852562808), (34, 0.077513509080...
4       [(0, 0.06817038680643188), (5, 0.1066488449838...
                              ...                        
6902                           [(5994, 0.14173977060375)]
6903                            [(5994, 0.2834795412075)]
6904                        [(5995, 0.36854338677274523)]
6905                         [(5999, 0.1549767656797962)]
6906                         [(5999, 0.1549767656797962)]
Name: tfidf_tuples, Length: 6907, dtype: object

To enhance convenience, we can store our second inverted index in a CSV file...

In [106]:
terms2.to_csv('inverted_index2.csv', index=False)

Now, we can proceed to develop the function for our second, more advanced search engine :

In [107]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def execute_query2(query, inverted_index, dataset, tfidf_data):
    # Preprocess the query to match the document processing
    query_terms = [porterstemmer.stem(word) for word in query.lower().split()]

    # Find documents that contain all terms in the query
    relevant_docs = set()
    for term in query_terms:
        if term in inverted_index['term'].values:
            docs_with_term = [doc_id for doc_id, _ in inverted_index.loc[inverted_index['term'] == term, 'tfidf_tuples'].iloc[0]]
            if not relevant_docs:
                relevant_docs = set(docs_with_term)
            else:
                relevant_docs.intersection_update(docs_with_term)

    if not relevant_docs:
        return pd.DataFrame()  # If no documents are found, return an empty DataFrame

    # Calculate cosine similarity for each document
    query_vec = tfidf.transform([' '.join(query_terms)])
    similarities = {}
    for doc_id in relevant_docs:
        doc_vec = tfidf_data.loc[doc_id].values.reshape(1, -1)
        similarities[doc_id] = cosine_similarity(query_vec, doc_vec)[0][0]

    # Sort documents by their similarity score
    sorted_doc_ids = sorted(similarities, key=similarities.get, reverse=True)

    # Prepare the results with the similarity score
    results = dataset.loc[sorted_doc_ids, ['courseName', 'universityName', 'description', 'url']]
    results['similarity'] = [similarities[doc_id] for doc_id in sorted_doc_ids]

    return results.reset_index(drop=True)

a first example would be :

In [111]:
results = execute_query2("advanced knowledge", terms2, dataset, tfidf_data)
(results)

courseName  \
0      Geo-information Science and Earth Observatio...   
1          Advanced Mechanical Engineering - MSc/PGDip   
2                       Air Transport Management (MSc)   
3      Advanced Nurse Practitioner/Professional Pra...   
4                   Gerontological Nursing - MSc/PgDip   
..                                                 ...   
444                       International Business - MSc   
445                            Diabetes Practice - MSc   
446                 Diabetes Practice MSc/PGDip/PGCert   
447                           Diagnostic Imaging - MSc   
448                         Diagnostic Radiography MSc   

                              universityName  \
0                       University of Twente   
1                     Heriot-Watt University   
2                       Cranfield University   
3    University of the Highlands and Islands   
4                     Trinity College Dublin   
..                                       ...   
444                    University of Glasgow   
445                       Cardiff University   
446                       Swansea University   
447            Glasgow Caledonian University   
448                  University College Cork   

                                           description  \
0    INTERESTED IN A CAREER IN SPATIAL DATA SCIENCE...   
1    This programme aims to develop the knowledge a...   
2    You can help solve the challenge as the aviati...   
3    Developed in partnership with expert clinical ...   
4    The aim of this course is to strengthen and de...   
..                                                 ...   
444  International Business will provide you with a...   
445  The MSc Diabetes Practice aims to equip health...   
446  If you are a health professional with a specia...   
447  Designed to train a new generation of leaders ...   
448  Our MSc Diagnostic Radiography programme is an...   

                                                   url  similarity  
0    https://www.findamasters.com/masters-degrees/c...    0.101751  
1    https://www.findamasters.com/masters-degrees/c...    0.060091  
2    https://www.findamasters.com/masters-degrees/c...    0.050153  
3    https://www.findamasters.com/masters-degrees/c...    0.046138  
4    https://www.findamasters.com/masters-degrees/c...    0.044068  
..                                                 ...         ...  
444  https://www.findamasters.com/masters-degrees/c...    0.000000  
445  https://www.findamasters.com/masters-degrees/c...    0.000000  
446  https://www.findamasters.com/masters-degrees/c...    0.000000  
447  https://www.findamasters.com/masters-degrees/c...    0.000000  
448  https://www.findamasters.com/masters-degrees/c...    0.000000  

[449 rows x 5 columns]

another example of use :

In [110]:
results = execute_query2("financial management", terms2, dataset, tfidf_data)
(results)

courseName  \
0                                  Master’s in Finance   
1              Master Financial Management and Control   
2                              Banking and Finance MSc   
3             Finance, Accounting and Management - MSc   
4                MSc Finance and Investment Management   
..                                                 ...   
231                       Accounting and Finance - MSc   
232                       Engineering Management (MSc)   
233    Master in Global Logistics and Supply Chain ...   
234                                  Master of Finance   
235                Construction Project Management MSc   

                                 universityName  \
0         Nova School of Business and Economics   
1      The Hague University of Applied Sciences   
2          Università Cattolica del Sacro Cuore   
3                        University of Bradford   
4                       University of Liverpool   
..                                          ...   
231  University of the West of England, Bristol   
232               University of Gloucestershire   
233           Kuehne Logistics University - KLU   
234                    York University (Canada)   
235                    University of Portsmouth   

                                           description  \
0    The Master’s in Finance prepares students for ...   
1    How do you keep a large organisation healthy? ...   
2    The Banking and Finance programme is a special...   
3    A Master's degree designed to produce fully ro...   
4    A career in finance and investment management ...   
..                                                 ...   
231  Today's business managers need to be able to a...   
232  The modules you will study include Leading Eng...   
233  Our MSc in Global Logistics and Supply Chain M...   
234  The “must-have” degree for specialized financi...   
235  Establish yourself in the global construction ...   

                                                   url  similarity  
0    https://www.findamasters.com/masters-degrees/c...    0.217332  
1    https://www.findamasters.com/masters-degrees/c...    0.112300  
2    https://www.findamasters.com/masters-degrees/c...    0.101381  
3    https://www.findamasters.com/masters-degrees/c...    0.082781  
4    https://www.findamasters.com/masters-degrees/c...    0.082547  
..                                                 ...         ...  
231  https://www.findamasters.com/masters-degrees/c...    0.000000  
232  https://www.findamasters.com/masters-degrees/c...    0.000000  
233  https://www.findamasters.com/masters-degrees/c...    0.000000  
234  https://www.findamasters.com/masters-degrees/c...    0.000000  
235  https://www.findamasters.com/masters-degrees/c...    0.000000  

[236 rows x 5 columns]